### ISSUE TITLE
Cannot start Tora 3.2.92

### ISSUE THREAD

**Issue by p91paul** [tora-tool/tora#103]
After downloading Tora.3.2.92.Release.64bit.msi if I try to start it I receive the following error:

![immagine](https://user-images.githubusercontent.com/2157006/41152594-6a6db252-6b14-11e8-8711-cab62ac58055.png)

3.2.82 works fine.

**Comment by ibre5041** [comment]
fixed. I compiled it agains Qt 5.11 but shipped it with Qt 5.10. Upgrade to latest version.
