### ISSUE TITLE
Can no longer build tora.

### ISSUE THREAD

**Issue by mgogala** [tora-tool/tora#105]
Building of the latest version fails on Ubuntu 18.04:

mgogala@umajor:~$ make-tora
-- The C compiler identification is GNU 7.3.0
-- The CXX compiler identification is GNU 7.3.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found Git: /usr/bin/git (found version "2.17.1") 
Git version v3.2-104-g27c57881
Git version major 3
Git version minor 2
Git version count 104
Git version sha1  g27c57881
Git version short 3.2
Git version dirty No
Git branch master
Build tag v3.2-104-Release-g27c57881
Build date 2018-06-20
-- Boost version: 1.65.1
-- Found the following Boost libraries:
--   system
-- Found Boost libraries for debug build: /usr/include; libs: /usr/lib/x86_64-linux-gnu
-- 
-- LIB_SUFFIX variable is not defined. It will be autodetected now.
-- You can set it manually with -DLIB_SUFFIX=<value> (64 for example)
-- CMAKE_SIZEOF_VOID_P=8
--  LIB_SUFFIX is set to '64'
-- 
-- Debug build
-- Found LOKI: /usr/lib/libloki.so  
-- Using external loki: headers=/usr/include libs=/usr/lib/libloki.so
Qt Found OK
QScintilla2 LIBPATH "/usr/lib/x86_64-linux-gnu;/usr/lib/;/usr/local/lib"
-- Found QScintilla2: /usr/lib/libqscintilla2_qt5.so
--          includes: /usr/include/x86_64-linux-gnu/qt5/Qsci
QScintilla2 Found OK
-- Guessed ORACLE_OCI_VERSION value: 12C for 122
-- ORACLE_LIBRARY_CLNTSH /usr/lib/instantclient_12_2/libclntsh.so
-- ORACLE_LIBRARY_CLNTST 
-- ORACLE_LIBRARY_OCCI 
-- ORACLE_LIBRARY_XML 
-- ORACLE_LIBRARY_OCIEI 
-- Found Oracle: /usr/lib/instantclient_12_2/libclntsh.so (ORACLE_HOME='/usr/lib/instantclient_12_2')
--     includes: /usr/lib/instantclient_12_2/sdk/include
-- Found XML Oracle:  
Oracle OCI Library Found OK
-- PostgreSQL advanced support is disabled by user choice
-- DB2 support is disabled by user choice
-- Teradata support disabled (enable with -DENABLE_TERADATA=on)
CMake Error at extlibs/libermodel/CMakeLists.txt:38 (QT4_WRAP_CPP):
  Unknown CMake command "QT4_WRAP_CPP".

-- Configuring incomplete, errors occurred!
See also "/home/mgogala/git/BUILD/CMakeFiles/CMakeOutput.log".
mgogala@umajor:~$ 

The problem seems to be in "Unknown CMake command "QT4_WRAP_CPP""

**Comment by ibre5041** [comment]
do you build against Qt4 or Qt5 ?

**Comment by mgogala** [comment]
QT5.
