### ISSUE TITLE
Feature request - bring back Tora2 "Auto indent" capability.

### ISSUE THREAD

**Issue by ZippyDufus** [tora-tool/tora#106]
Tora2 had an outstanding feature **Edit->Auto indent** whereby the user could highlight an SQL query and it would reformat (beautify) it.

In Tora3, the user can highlight a query, right-mouse-click and choose **Indent** but this doesn't work very well.

```
 select
  *
  from
   bogus
```
I'm a heavy user of Tora and have always used this feature to inspect and review application-generated SQL retrieved from Oracle **SGA Trace** or, more recently, from queries retrieved from the MSSQL (via ODBC) query cache.

== // ==

Side note, I am now using DIY-built Tora3 on Fedora 28 as my daily driver and it is performing well.  Thanks!

**Comment by ibre5041** [comment]
it is complicated. the old indentation code was based on broken parser. implementing a new indentation tool requires plenty of work. the "new" indent so far is just a "study" it determines indentation for each word from depth in AST parse tree. Therefore I put each word in separate line. There is still plenty of work to implement it properly.

**Comment by ibre5041** [comment]
I commited some changes, but it is still a long way to go

**Comment by ibre5041** [comment]
initial support for indentation of Oracle's SQL was committed.
