### ISSUE TITLE
Ubuntu 18.04 compilation fails

### ISSUE THREAD

**Issue by mgogala** [tora-tool/tora#116]
/home/mgogala/git/tora/src/widgets/toaboutcopying.cpp: In constructor ‘toAboutCopying::toAboutCopying(QWidget*, const char*)’:
/home/mgogala/git/tora/src/widgets/toaboutcopying.cpp:84:9: error: ‘QFileInfo’ was not declared in this scope
         QFileInfo GvToraDir(QCoreApplication::applicationDirPath() + QDir::separator() + "Graphviz2.38" + QDir::separator() + "bin");
         ^~~~~~~~~
/home/mgogala/git/tora/src/widgets/toaboutcopying.cpp:84:9: note: suggested alternative: ‘QFontInfo’
         QFileInfo GvToraDir(QCoreApplication::applicationDirPath() + QDir::separator() + "Graphviz2.38" + QDir::separator() + "bin");
         ^~~~~~~~~
         QFontInfo
/home/mgogala/git/tora/src/widgets/toaboutcopying.cpp:85:21: error: ‘GvToraDir’ was not declared in this scope
         QString p = GvToraDir.absoluteFilePath();
                     ^~~~~~~~~
make[3]: *** [src/CMakeFiles/tora.dir/widgets/toaboutcopying.cpp.o] Error 1
make[3]: *** Waiting for unfinished jobs....
make[2]: *** [src/CMakeFiles/tora.dir/all] Error 2
make[1]: *** [src/CMakeFiles/tora.dir/rule] Error 2
make: *** [tora] Error 2

I have installed GraphViz 2.40 with development libraries.

**Comment by yp-warsaw** [comment]
Hello,
i had the same problem on Fedora. To solve it, i modified the file src/widgets/toaboutcopying.cpp
and added the following 2 lines (at the beginning just after #include <QtCore/QFile>) :

#include <QtCore/QFileInfo>
#include <QtCore/QDir>

and it worked.

**Comment by ibre5041** [comment]
Just create a pull request I will merge it.

**Comment by mgogala** [comment]
Yup, that does it. Those two lines have fixed the Ubuntu 19.04 compilation as well.

**Comment by yp-warsaw** [comment]
Ok i  just did the pull request. It is my first time with github so I hope I didnt do something wrong :)
By the way, thanks for developing Tora : it is a great software  and a very useful and powerful tool !

**Comment by ibre5041** [comment]
Pull request merged.

btw ywc. If you have more fixes/enhancements feel free to send more patches.
