### ISSUE TITLE
File not saved while closing TOra

### ISSUE THREAD

**Issue by Sergiomdf** [tora-tool/tora#119]
I found this problem using Tora v3.2-146-g4da93df1 64bit on Windows 10.

Steps to reproduce
1. Open TOra and connect to a database, write a query, execute it and see the results.
2. Close TOra main window. It asks to save the changes in the not-saved-before editor, choose "Save".
3. Save file dialog opens, write a file name and accept.
4. TOra closes, the choosed file name appears in Windows Explorer "recent files" but it's not in the folder it should be.

**Comment by ibre5041** [comment]
fixed. thx for reporting it.
