### ISSUE TITLE
Qt5: missed include in tooraclesetting.cpp

### ISSUE THREAD

**Issue by ssten** [tora-tool/tora#124]
TOra again fails to build with recent stable Qt. See bug [#674874](https://bugs.gentoo.org/674874)

Suggested patch [here](https://674874.bugs.gentoo.org/attachment.cgi?id=560958).

**Comment by ssten** [comment]
Thank you!

For me it builds.
Reporter also confirmed it.

**Comment by ssten** [comment]
BTW: latest release os over year ago and incompatible with recent vertsions of Qt5 library.

Maybe, it's a time to renew it?

**Comment by ibre5041** [comment]
You mean latest release for Linux? Which distribution? Unfortinatelly nobody maintains Tora packages in distributions and the process of becoming one is complicated. I also tried to build Flatpack packages, but Flatpack did not contain QtSql library and other sql drivers.
