### ISSUE TITLE
Please tag point releases

### ISSUE THREAD

**Issue by peterhoeg** [tora-tool/tora#125]
According to ```NEWS```, the latest version is ```3.2.176``` but the latest tagged release is ```3.2``` from 2017.

**Comment by ibre5041** [comment]
I created that relase when I finished major changes in the code. The lastest version 3.2.176 is 176 commits since I created that tag. I use git to generate version number.

**Comment by peterhoeg** [comment]
I assume that people are supposed to be running the latest point release (3.2.176) and not 3.2? Is there any particular reason then not just to tag the 3.2.176 as well? I am packing this for NixOS and therefore subscribe to the ```releases.atom``` feed to be notified of new versions - this is much easier then having to dig through a NEWS file to check for updates so I'd really appreciate it.

**Comment by peterhoeg** [comment]
So any chance we can start seeing the 3.2.x releases tagged as well?
