### ISSUE TITLE
Fails to build: error: ‘struct toQueryAbstr::HeaderDesc’ has no member named ‘name_orig’

### ISSUE THREAD

**Issue by mitya57** [tora-tool/tora#128]
When I am trying to build the latest version from Git master, I get this error:
```
[ 82%] Building CXX object src/CMakeFiles/tora.dir/core/toproviderobserver.cpp.o
/home/dmitry/upstream/tora/src/core/toproviderobserver.cpp: In member function ‘virtual void toEventQueryObserverObject::eqDescriptionAvailable(toEventQuery*, const toQColumnDescriptionList&)’:
/home/dmitry/upstream/tora/src/core/toproviderobserver.cpp:79:11: error: ‘struct toQueryAbstr::HeaderDesc’ has no member named ‘name_orig’
         d.name_orig = (*i).Name;
           ^~~~~~~~~
```

This is with Debian unstable, GCC 8.3.0, Oracle client libraries 12.2.0.1.0.

After commenting out that line, it builds fine.

**Comment by mgogala** [comment]
My issue with Ubuntu 18.04 is the very same one. When I applied your recipe, the build succeeded.

**Comment by ZippyDufus** [comment]
Did your builds work properly?  It appears that this is this is used.  Perhaps commenting back in the TODO would be better.

```
$ grep -r name_orig *
src/core/toproviderobserver.cpp:        d.name_orig = (*i).Name;
src/widgets/toresultmodel.cpp:    d.name_orig = d.name;
src/widgets/toresultmodel.cpp:    d.name_orig = type + " name";
src/widgets/toresultmodel.cpp:        if (Headers[c].name_orig == column)
src/widgets/toresultmodel.cpp:    Headers[section].name_orig = value.toString();
src/widgets/toresultmodel.cpp:    d.name_orig = d.name;
src/widgets/toresultmodel.cpp:        d.name_orig = d.name;
src/widgets/toresultmodel.h:            QString           name_orig;   /* original column name */
src/result/tomvc.h:        //d.name_orig = QString("#"); TODO
```

**Comment by mitya57** [comment]
I was using Tora for the first time, but I did not notice anything unusual. I was able to run some queries on Oracle server.

**Comment by ZippyDufus** [comment]
> I was using Tora for the first time, but I did not notice anything unusual. I was able to run some queries on Oracle server.

Yup, built and runs for me on Fedora 29.

It looks like there is some code refactoring going on and the intention was to comment out that problem line just like the last line in my grep above.

Thanks.


GITVERSION: | v3.2-197-g099246e7-dirty
-- | --
GITVERSION_MAJOR: | 3
GITVERSION_MINOR: | 2
GIT_BUILD_TYPE: | Release
GITVERSION_COUNT: | 197
GITVERSION_SHA1: | g099246e7
GITVERSION_SHORT: | 3.2
GIT_BRANCH: | master
BUILD_TAG: | v3.2-197-Release-g099246e7-dirty
BUILD_DATE: | 2019-03-21
