### ISSUE TITLE
Autocomplete duplicates schema

### ISSUE THREAD

**Issue by mkyral** [tora-tool/tora#133]
When I select a table from the autocomplete list it add already entered schema, so schema is duplicated.

Steps:
1) Write schema name with dot
2) Select a table from autocomplete list

Expected result: the SCHEMA will be shown only once (SCHEMA.TABLE)
Current result: schema is duplicated (SCHEMA.SCHEMA.TABLE)

![obrazek](https://user-images.githubusercontent.com/155542/59675104-e26e2e80-91c4-11e9-82fe-3942ae6017ca.png)

![obrazek](https://user-images.githubusercontent.com/155542/59675347-5f99a380-91c5-11e9-8cf2-10abf8bd9c16.png)

I'm using the latest Tora from git with several Oracle DB versions (10, 12...)

**Comment by ibre5041** [comment]
fixed by 0225cfeb62e09226cbaf446fe095f6357cf4b8fc
