### ISSUE TITLE
Fail to update values with mixed cases field name through HMI

### ISSUE THREAD

**Issue by eraso** [tora-tool/tora#149]
Hello,

With Tora 3.2.186/windows/x64, while trying to update values of fields directly / interactively through HMI, it failed.

The problem is with mixed cases (lower and upper case) field names.
If such field names are'nt protected with double quotes, the field name is considered in upper case.
The field name with mixed cases is totally different with the "almost same" field name in uppercase.
For instance, the table Fee declares a field name called "Price".
If you try to update the value of "Price" field of the "Fee" table through HMI, the request sended to Oracle Server is :
update "Fee" set Price=0.01 where ...
But the request should be like :
update "Fee" set "Price"=0.01 where ...

KR,

eraso

**Comment by ibre5041** [comment]
Fixed in trunk.
