### ISSUE TITLE
Download Links Never Go Anywhere

### ISSUE THREAD

**Issue by absolutesantaja** [tora-tool/tora#16]
Can you please update the download page so that it actually goes somewhere. Right now if you click on the Windows build download it just loops you back to the wiki where there isn't an actual download link.

**Comment by KenMiles** [comment]
If you copy the text of the link and paste into browser they get you somewhere close
[http://sourceforge.net/projects/tora/files/tora/](http://sourceforge.net/project/showfiles.php?group_id=16636) takes you to Windows Downloads
[http://sourceforge.net/projects/tora/files/tora/tora_documentation.pdf/download.](http://sourceforge.net/projects/tora/files/tora/tora_documentation.pdf/download) is Documentation

**Comment by ibre5041** [comment]
Can you please more elaborate on this? I mean download page on SF?

**Comment by absolutesantaja** [comment]
When I last went to home page clicking the download link would send you to the wiki. The download link on the wiki went back to the homepage. So there was no clear path to the sf download.

Sent from my iPhone

On Mar 29, 2016, at 11:24 AM, Ivan Brezina <notifications@github.com<mailto:notifications@github.com>> wrote:


Can you please more elaborate on this? I mean download page on SF?

-

**Comment by ibre5041** [comment]
solved
