### ISSUE TITLE
Unreadable text in About window with dark schema

### ISSUE THREAD

**Issue by mkyral** [tora-tool/tora#20]
The About dialog sets bacground but does not sets font color, so with dark qt theme I get light gray text on orange. 

![tora_black_scheme](https://cloud.githubusercontent.com/assets/155542/13597942/6ae2b740-e51b-11e5-93d6-cc6714c848d4.png)

**Comment by ibre5041** [comment]
You're right the dark theme looks ugly. Moreover the qscintilla part is unusable. It shows black letters on black background. Some time ago somebody recommended me some qt5 class which finally allows you so access attributes of current system theme. Unfortunately I can not find it anymore.

I'm quite  sure, there is no way how to get current system theme attributes in qt4, but something was added into qt5.

**Comment by mkyral** [comment]
Well, I think this is not about current schema, but about changing font color when there is a change of background color.

The current version of Tora does looks more less correct on dark system theme. This is currently the biggest issue.

**Comment by mkyral** [comment]
I see this was fixed in 13f56ac6.

Thanks.
