### ISSUE TITLE
Bindings

### ISSUE THREAD

**Issue by jods4** [tora-tool/tora#24]
TOra behaves _as if_ it supports bindings. 
If I execute:
```sql
select :test from dual
```
Then a popup appears and asks for the `:test` parameter value.

But then when it tries to execute the query it fails with:
```
error at SQL position 7 [1.8]:
select 
       ^

last SQL statement:
select 


mar. avr. 5 20:29:30 2016

ORA-00936: missing expression
```

**Comment by ibre5041** [comment]
Fixed by a7e0adc4440a41cc1d264a08d98e4bbd00742231

**Comment by jods4** [comment]
That was fast! :clap: 
I am new to TOra (which looks _very_ promising), can I ask you what the delivery channel is for such fixes is?

How often do you release? Is there a "nightly" channel? 

Asking because binds are really a must-have feature for me.

**Comment by ibre5041** [comment]
There was something like nightly builds for Linux rpms. But nothing for Windows. I'll try to make packages during the weekend.
