### ISSUE TITLE
query via database link does not work (windows 64bit tora3 )

### ISSUE THREAD

**Issue by leeuwke** [tora-tool/tora#25]
when I do a query using a database link, the database link part is ignored.
eg.
I have a dev database and a test database with the same schema
when connected with the test database :
select count(*) from table@DEV
gives the results from :
select count(*) from table

specifying a database link that does not exist, does not give an error
select count(*) from table@XXX

it seems dat the databaselink part is ignored in the query

tora 2.1.3 (32 bit) does work correctly.

**Comment by ibre5041** [comment]
fixed by d04bcec596dc9f6aab4dcc5cf674da9daadc3797.

**Comment by leeuwke** [comment]
thx for the quick fix!
