### ISSUE TITLE
How to change format of postgres timestamp

### ISSUE THREAD

**Issue by diskin** [tora-tool/tora#34]
This is not an issue, but a question. I can't find a way to specify format for timestamp values. Specifically, I'd like to see seconds. Is it possible? TOra 2.1.3

**Comment by ibre5041** [comment]
What exactly do you want to see? PostgreSQL connection provider uses QSql layer. This converts database datatype TIMESTAMP into QDateTime. Calling QDateTime::toString() probably somehow respects system locales. For me in Windows I get:

    select now();
    ==============
    2016-05-10T22:34:09

At least on Tora ver. 3.0.

**Comment by diskin** [comment]
In the table I see "5/10/16 10:56 AM", but when I hover mouse over the data, it shows 2016-05-10T10:56:11. Also, it is exported in the right format. So, it's just the data grid which shows it formatted. Screenshot attached. This is in TOra 2.1.3 on Linux.

![tora](https://cloud.githubusercontent.com/assets/7723699/15162036/8c56da4e-1709-11e6-9df7-cd79e23845e7.png)

**Comment by ibre5041** [comment]
And what about version 3.0? Version 2.1.3 is not maintained any more.

**Comment by diskin** [comment]
Seems that the output format depends on LC_TIME variable. If I run TOra as:
`LC_TIME="POSIX" tora` - I see seconds. 

Re: version 3, I use Ubuntu and it still has `2.1.3-2build5` in repositories...

**Comment by ibre5041** [comment]
The whole project was stalled for some time. We are no more in contact with package maintainers. And I doubt we will ever get back into distributions like Debian or Fedora. You can still compile sources by your own, or you can download .deb packages from sourceforge. From time to time I upload refreshed builds.

**Comment by diskin** [comment]
Closing, outdated
