### ISSUE TITLE
Can't save blob as file

### ISSUE THREAD

**Issue by scastillobib** [tora-tool/tora#36]
Hi!

I'm using tora  2.1.3 from debian repositories. I had to build it from source to enable Oracle connector.

I can connect to databases and it works well but i can't save blob values as files. They are showed as (corrupted) ASCII strings.

Is it possible to save blob as files? 

Thank you and regards.

**Comment by ibre5041** [comment]
Try version 3. Either compile it by your own or download .deb package from sourceforge.

**Comment by scastillobib** [comment]
I have a 32 bit system and deb files are 64 bit builds. I´m trying to compile from source but i get an error at 4% (tora-master/extlibs/trotl/src/trotl_lob.h:117:2: error: ‘oraub8’ does not name a type)

Any idea?

Thank you and regards.

**Comment by ibre5041** [comment]
oraub8 is datatype defined by Oracle OCI driver. It defines 64bit unsigned int. To be used as LOB offset while reading/writing. Which version of OCI drivers are you using?

**Comment by scastillobib** [comment]
I'm using 10.2.0.5 instant client and sdk.

I have exported ORACLE_HOME and TNS_ADMIN environment variables and cmake successfully found the libraries and header directories.

Should I use a newer thin client?.
will tora 2.1.3 works fine wine blob (I mean been able to save blob as files) with a newer oracle libraries?

Regards.

**Comment by scastillobib** [comment]
I have update instant client (12.1.0.2.0) and now tora 3 builds successfully.

But, anway, I can´t save blob as files.

Can tora save blob values as files?

Regars.

**Comment by ibre5041** [comment]
When you click (double click) on a value in the grid. Then, when you're in memo editor, click on "Save" icon,

**Comment by scastillobib** [comment]
It works perfectly with tora 3. Thank you very much.

**Comment by ibre5041** [comment]
Note: Tora2 had internal limitation, it could display and save up to 20000 bytes of the LOB. Tora3 displays also only leading bytes, but safe should put into the file the whole lob regardless of it's size.
