### ISSUE TITLE
Make error on Arch Linux, build failed

### ISSUE THREAD

**Issue by nydn** [tora-tool/tora#37]
Hey there,

Trying to build master on Arch fails.
`$uname -a`
`Linux arch-desktop 4.5.4-1-ARCH #1 SMP PREEMPT Wed May 11 22:21:28 CEST 2016 x86_64 GNU/Linux`

qt5-base-5.6.0-6 [installed]
qt5-tools-5.6.0-2 [installed]
qscintilla-qt5 2.9.1-3 [installed]
boost 1.60.0-5 [installed]
loki-lib-0.1.7-2 [installed]
oracle-instantclient-basic 12.1.0.2.0-1 [installed]
oracle-instantclient-sdk 12.1.0.2.0-1 [installed]
cmake 3.5.2-2 [installed]
gcc-multilib 6.1.1-1 [installed]

After cloning:

`[dani@arch-desktop RBUILD]$ cmake -DBOOST_ROOT=/usr/include -DCMAKE_INSTALL_PREFIX:PATH=/home/dani/torasql -DENABLE_PGSQL=0 -DCMAKE_BUILD_TYPE=Release ../../tora`
> -- The C compiler identification is GNU 6.1.1
> -- The CXX compiler identification is GNU 6.1.1
> -- Check for working C compiler: /usr/bin/cc
> -- Check for working C compiler: /usr/bin/cc -- works
> -- Detecting C compiler ABI info
> -- Detecting C compiler ABI info - done
> -- Detecting C compile features
> -- Detecting C compile features - done
> -- Check for working CXX compiler: /usr/bin/c++
> -- Check for working CXX compiler: /usr/bin/c++ -- works
> -- Detecting CXX compiler ABI info
> -- Detecting CXX compiler ABI info - done
> -- Detecting CXX compile features
> -- Detecting CXX compile features - done
> -- Found Git: /usr/bin/git (found version "2.8.3") 
> Git version v3.0-59-g49b6b02
> Git version major 3
> Git version minor 0
> Git version count 59
> Git version sha1  g49b6b02
> Git version short 3.0
> Git version dirty 
> Git branch master
> Build tag v3.0-59-Release-g49b6b02
> Build date 2016-05-26
> -- Boost version: 1.60.0
> -- Found the following Boost libraries:
> -- system
> -- Found Boost libraries for debug build: /usr/include; libs: /usr/lib64
> -- LIB_SUFFIX variable is not defined. It will be autodetected now.
> -- You can set it manually with -DLIB_SUFFIX=<value> (64 for example)
> -- CMAKE_SIZEOF_VOID_P=8
> -- LIB_SUFFIX is set to '64'
> -- non-debug build
> -- Found LOKI: /usr/lib64/libloki.so  
> -- Using external loki: headers=/usr/include libs=/usr/lib64/libloki.so
> Qt Found OK
> QScintilla2 LIBPATH "/usr/lib;/usr/lib/;/usr/local/lib"
> -- Found QScintilla2: /lib64/libqscintilla2-qt5.so
> --          includes: /usr/include/qt/Qsci
> QScintilla2 Found OK
> -- Guessed ORACLE_OCI_VERSION value: 12C for 121
> -- ORACLE_LIBRARY_CLNTSH /usr/lib64/libclntsh.so
> -- ORACLE_LIBRARY_CLNTST 
> -- ORACLE_LIBRARY_OCCI 
> -- ORACLE_LIBRARY_XML 
> -- ORACLE_LIBRARY_OCIEI 
> -- Found Oracle: /usr/lib64/libclntsh.so (ORACLE_HOME='/usr')
> --     includes: /usr/include
> -- Found XML Oracle:  
> Oracle OCI Library Found OK
> -- PostgreSQL advanced support is disabled by user choice
> -- DB2 support is disabled by user choice
> -- Teradata support disabled (enable with -DENABLE_TERADATA=on)
> -- Oracle OCI Library Found OK
> -- -- No Oracle XDK found: ignoring
> -- poracle /usr/lib64/libclntsh.so   trotl
> -- Found Doxygen: /bin/doxygen (found version "1.8.11") 
> -- Developer documentation (doxygen) can be generated by 'make docs'
> -- TOra 3.0 will be built & installed into /home/dani/torasql
> -- Configuring done
> -- Generating done
> -- Build files have been written to: /home/dani/Downloads/tora3/RBUILD

`[dani@arch-desktop RBUILD]$ make tora poracle`

> [  0%] Generating moc_dotgraph.cpp
> [  0%] Generating moc_canvasedge.cpp
> [  0%] Generating moc_canvaselement.cpp
> [  0%] Generating moc_canvasnode.cpp
> [  0%] Generating moc_graphelement.cpp
> [  0%] Generating moc_dotgraphview.cpp
> [  1%] Generating moc_pannerview.cpp
> Scanning dependencies of target ermodel
> [  1%] Building CXX object extlibs/libermodel/CMakeFiles/ermodel.dir/canvasedge.cpp.o
> In file included from /usr/include/qt/QtCore/qnamespace.h:37:0,
>                  from /usr/include/qt/QtCore/qobjectdefs.h:41,
>                  from /usr/include/qt/QtCore/qobject.h:40,
>                  from /usr/include/qt/QtWidgets/qgraphicsscene.h:37,
>                  from /usr/include/qt/QtWidgets/QGraphicsScene:1,
>                  from /home/dani/Downloads/tora/extlibs/libermodel/canvasedge.h:31,
>                  from /home/dani/Downloads/tora/extlibs/libermodel/canvasedge.cpp:28:
> /usr/include/qt/QtCore/qglobal.h:1090:4: error: #error "You must build your code with position independent code if Qt was built with -reduce-relocations. " "Compile your code with -fPIC (-fPIE is not enough)."
>  #  error "You must build your code with position independent code if Qt was built with -reduce-relocations. "\
>     ^~~~~
> /home/dani/Downloads/tora/extlibs/libermodel/canvasedge.cpp:149:48: warning: "/*" within comment [-Wcomment]
>                (dro.integers[2*i+1]/ *%m_wdhcf* /*m_scaleX) +m_xMargin + diffX,
>                                                  
> extlibs/libermodel/CMakeFiles/ermodel.dir/build.make:90: recipe for target 'extlibs/libermodel/CMakeFiles/ermodel.dir/canvasedge.cpp.o' failed
> make[3]: *** [extlibs/libermodel/CMakeFiles/ermodel.dir/canvasedge.cpp.o] Error 1
> CMakeFiles/Makefile2:239: recipe for target 'extlibs/libermodel/CMakeFiles/ermodel.dir/all' failed
> make[2]: *** [extlibs/libermodel/CMakeFiles/ermodel.dir/all] Error 2
> CMakeFiles/Makefile2:382: recipe for target 'src/CMakeFiles/tora.dir/rule' failed
> make[1]: *** [src/CMakeFiles/tora.dir/rule] Error 2
> Makefile:262: recipe for target 'tora' failed
> make: *** [tora] Error 2

**Comment by ibre5041** [comment]
Are you able to fix it by your own? This is really corner case where various cmake are not too compatible. And also various Qt5 subversions and various QT build make it really hard to make the code portable. Theoretically the macro Qt5_POSITION_INDEPENDENT_CODE should do it. It should contain macros used for compilation and thus the same macros should be appended to build's CXX_FLAGS.

On most platforms Qt5_POSITION_INDEPENDENT_CODE is not needed, or maybe even defined.
Please try to put something like:
MESSAGE(STATUS " Qt5_POSITION_INDEPENDENT_CODE ${Qt5_POSITION_INDEPENDENT_CODE}")

Somewhere into the top level CMakeList.txt to see if and how this macro is defined. 2nd step would be to append this macro to CMAKE_CXX_FLAGS.

**Comment by nydn** [comment]
Uncommented the part

```
 if (Qt5_POSITION_INDEPENDENT_CODE)
   SET(CMAKE_POSITION_INDEPENDENT_CODE ON)
 endif()
```
at line 230 in CMakeLists.txt solved the problem and was able to make and install tora. Thanks for your comment it helped me. I should have been more aware.

I'm getting a lot of libtrotl.so: undefined symbol error on Tora startup, but it works after that.
(However I can only select MySQL(QSql)/ODBC(QSql)/PgSQL(QSql) in Connection Provider. I assume there should be a native Oracle one. But thats another issue).

**Comment by ibre5041** [comment]
it says undefined symbol, but does not tell which one?

**Comment by nydn** [comment]
Sorry, I left that out:

torasql/lib64/libtrotl.so: undefined symbol: _ZN5boost6system15system_categoryEv

It's the same after recompile.

**Comment by ibre5041** [comment]
Ok it looks like you use newer version of boost. Until now we used header-only parts of boost. Since some boost release we also have to link against boost-system library.
Something like this has to implemented:
http://stackoverflow.com/a/12285571/836215

**Comment by mkyral** [comment]
> Uncommented the part
> 
>  ```if (Qt5_POSITION_INDEPENDENT_CODE)
   SET(CMAKE_POSITION_INDEPENDENT_CODE ON)
 endif()```
> 
> at line 230 in CMakeLists.txt solved the problem and was able to make and install tora. Thanks for  your comment it helped me. I should have been more aware.

I have the same issue on my Gentoo.  And this fixed it for me as well.
I'm using Qt 5.6 and bundled QScintilla as there is no Qt5 version of QScintilla in Gentoo yet.

```bash
>>> Emerging (1 of 1) dev-db/tora-9999::mkyral
>>> Unpacking source...
GIT update -->
   repository:               https://github.com/tora-tool/tora.git
   at the commit:            49b6b02bcbb65d0923acdf4d1299eab3f4c06341
   branch:                   master
   storage directory:        "/usr/portage/distfiles/egit-src/tora.git"
   checkout type:            bare repository
Cloning into '/var/tmp/portage/dev-db/tora-9999/work/tora-9999'...
done.
Branch branch-master set up to track remote branch master from origin.
Switched to a new branch 'branch-master'
>>> Unpacked to /var/tmp/portage/dev-db/tora-9999/work/tora-9999
>>> Source unpacked in /var/tmp/portage/dev-db/tora-9999/work
>>> Preparing source in /var/tmp/portage/dev-db/tora-9999/work/tora-9999 ...
 * Applying fix_fPIC_issue.patch ...       [ ok ]
>>> Source prepared.
>>> Configuring source in /var/tmp/portage/dev-db/tora-9999/work/tora-9999 ...
>>> Working in BUILD_DIR: "/var/tmp/portage/dev-db/tora-9999/work/tora-9999_build"
cmake --no-warn-unused-cli -C /var/tmp/portage/dev-db/tora-9999/work/tora-9999_build/gentoo_common_config.cmake -G Unix Makefiles -DCMAKE_INSTALL_PREFIX=/usr -DENABLE_ORACLE=ON -DWANT_RPM=OFF -DWANT_BUNDLE=OFF -DWANT_BUNDLE_STANDALONE=OFF -DWANT_INTERNAL_QSCINTILLA=ON -DWANT_INTERNAL_LOKI=OFF -DLOKI_LIBRARY=/usr/lib64/libferrisloki.so -DLOKI_INCLUDE_DIR=/usr/include/FerrisLoki -DENABLE_PGSQL=ON -DWANT_debug=OFF -DWANT_DEBUG=OFF -DWANT_Debug=OFF -DTORA_DOC_DIR=share/doc/tora-9999 -DCMAKE_BUILD_TYPE=Gentoo -DCMAKE_INSTALL_DO_STRIP=OFF -DCMAKE_USER_MAKE_RULES_OVERRIDE=/var/tmp/portage/dev-db/tora-9999/work/tora-9999_build/gentoo_rules.cmake -DCMAKE_TOOLCHAIN_FILE=/var/tmp/portage/dev-db/tora-9999/work/tora-9999_build/gentoo_toolchain.cmake  /var/tmp/portage/dev-db/tora-9999/work/tora-9999
Not searching for unused variables given on the command line.
loading initial cache file /var/tmp/portage/dev-db/tora-9999/work/tora-9999_build/gentoo_common_config.cmake
-- The C compiler identification is GNU 4.9.3
-- The CXX compiler identification is GNU 4.9.3
-- Check for working C compiler: /usr/bin/x86_64-pc-linux-gnu-gcc
-- Check for working C compiler: /usr/bin/x86_64-pc-linux-gnu-gcc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/x86_64-pc-linux-gnu-g++
-- Check for working CXX compiler: /usr/bin/x86_64-pc-linux-gnu-g++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found Git: /usr/bin/git (found version "2.7.3") 
Git version v3.0-59-g49b6b02-dirty
Git version major 3
Git version minor 0
Git version count 59
Git version sha1  g49b6b02
Git version short 3.0
Git version dirty -dirty
Git branch branch-master
Build tag v3.0-59-Release-g49b6b02-dirty
Build date 2016-05-27
CMake Warning at cmake/modules/getgit.cmake:81 (message):
  Git version dirty: v3.0-59-g49b6b02-dirty
Call Stack (most recent call first):
  CMakeLists.txt:64 (include)


-- Boost version: 1.56.0
-- Found the following Boost libraries:
--   system
-- Found Boost libraries for debug build: /usr/include; libs: /usr/lib64
-- non-debug build
-- Found LOKI: /usr/lib64/libferrisloki.so  
-- Using external loki: headers=/usr/include/FerrisLoki libs=/usr/lib64/libferrisloki.so
Qt Found OK
-- QSci: Building with internal copy of QScintilla.
-- QSci: It's recomended to use external library for it
-- Guessed ORACLE_OCI_VERSION value: 10G_R2 for 102
-- ORACLE_LIBRARY_CLNTSH /usr/lib64/oracle/10.2.0.5.0/client/lib/libclntsh.so
-- ORACLE_LIBRARY_CLNTST 
-- ORACLE_LIBRARY_OCCI 
-- ORACLE_LIBRARY_XML 
-- ORACLE_LIBRARY_OCIEI 
-- Found Oracle: /usr/lib64/oracle/10.2.0.5.0/client/lib/libclntsh.so (ORACLE_HOME='/usr/lib64/oracle/10.2.0.5.0/client')
--     includes: /usr/lib64/oracle/10.2.0.5.0/client/rdbms/public
-- Found XML Oracle:  
Oracle OCI Library Found OK
-- Found PostgreSQL: /usr/include  
-- PostgreSQL environment found: /usr/include /usr/lib64/libpq.so
-- DB2 support is disabled by user choice
-- Teradata support disabled (enable with -DENABLE_TERADATA=on)
-- Oracle OCI Library Found OK
-- -- No Oracle XDK found: ignoring
-- poracle /usr/lib64/oracle/10.2.0.5.0/client/lib/libclntsh.so   trotl
-- Found Doxygen: /usr/bin/doxygen (found version "1.8.10") 
-- 
-- Developer documentation (doxygen) can be generated by 'make docs'
-- 
-- TOra 3.0 will be built & installed into /usr
-- <<< Gentoo configuration >>>
Build type      Gentoo
Install path    /usr
Compiler flags:
C               -Wall            -ggdb3   
C++             -Wall -std=c++11 -ggdb3 
Linker flags:
Executable       -Wl,-O1 -Wl,--as-needed
Module           -Wl,-O1 -Wl,--as-needed
Shared           -Wl,-O1 -Wl,--as-needed

```

I have no issue with missing Oracle Connection provider and there are no undefined symbols on start (but I have older boost):

```
$ tora
QObject::connect: No such slot toMain::addConnection(toConnection *conn, bool)
QObject::connect: No such slot toWorksheet::slotChangeRefresh(const QString &)
QObject::connect:  (sender name:   'toRefreshCombo')
QObject::connect:  (receiver name: 'toWorksheet')
QObject::moveToThread: Current thread (0x2edecb0) is not the object's thread (0x2a69ab0).
Cannot move to target thread (0x2edecb0)

QObject::connect: No such slot toResultPlanView::slotStop()
QObject::moveToThread: Current thread (0x2ee11a0) is not the object's thread (0x2a69ab0).
Cannot move to target thread (0x2ee11a0)

QObject::moveToThread: Current thread (0x2d65060) is not the object's thread (0x2a69ab0).
Cannot move to target thread (0x2d65060)

QObject::moveToThread: Current thread (0x3081d20) is not the object's thread (0x2a69ab0).
Cannot move to target thread (0x3081d20)

QObject::connect: No such slot toResultPlanModel::slotErrorHanler(toEventQuery*, toConnection::exception const &)
QObject::moveToThread: Current thread (0x3133f50) is not the object's thread (0x2a69ab0).
Cannot move to target thread (0x3133f50)
```

**Comment by nydn** [comment]
> Ok it looks like you use newer version of boost. Until now we used header-only parts of boost. Since some boost release we also have to link against boost-system library.

I just can't seem do that properly.
I have `FIND_PACKAGE(Boost REQUIRED COMPONENTS system)`

and if I'm thinkinh right I have to extend e.g.
```
IF (Boost_FOUND)
    MESSAGE(STATUS "Found Boost libraries for debug build: ${Boost_INCLUDE_DIRS}; libs: ${Boost_LIBRARY_DIRS}")                 
...
```
with `target_link_libraries(TARGET ${Boost_SYSTEM_LIBRARY})`
but for TARGET if I use ${TARGET} it fails,or if I use tora it also fails on cmake.
If I want to add `add_executable(target ...)` before linking the target what file should I use?
(Sorry, I'm not familiar with cmake and cpp)

**Comment by ibre5041** [comment]
Can you pls try this patch a18bfe496ed4a3d1a09b4139050254829ea3e672 , does it work for you?

**Comment by nydn** [comment]
Well, it looks like I have another error on make with the v.3.0.fixes branch (I've only tried the master branch before).

```
[ 95%] Building CXX object src/CMakeFiles/tora.dir/tools/toawr.cpp.o
/home/dani/Downloads/tora/src/tools/toawr.cpp: In member function ‘virtual void toAWR::closeEvent(QCloseEvent*)’:
/home/dani/Downloads/tora/src/tools/toawr.cpp:403:10: error: invalid use of incomplete type ‘class QCloseEvent’
     event->accept();
          ^~
In file included from /usr/include/qt/QtWidgets/QWidget:1:0,
                 from /home/dani/Downloads/tora/src/widgets/totoolwidget.h:46,
                 from /home/dani/Downloads/tora/src/tools/toawr.h:38,
                 from /home/dani/Downloads/tora/src/tools/toawr.cpp:35:
/usr/include/qt/QtWidgets/qwidget.h:73:7: note: forward declaration of ‘class QCloseEvent’
 class QCloseEvent;
       ^~~~~~~~~~~
src/CMakeFiles/tora.dir/build.make:9616: recipe for target 'src/CMakeFiles/tora.dir/tools/toawr.cpp.o' failed
make[3]: *** [src/CMakeFiles/tora.dir/tools/toawr.cpp.o] Error 1
CMakeFiles/Makefile2:338: recipe for target 'src/CMakeFiles/tora.dir/all' failed
make[2]: *** [src/CMakeFiles/tora.dir/all] Error 2
CMakeFiles/Makefile2:350: recipe for target 'src/CMakeFiles/tora.dir/rule' failed
make[1]: *** [src/CMakeFiles/tora.dir/rule] Error 2
Makefile:249: recipe for target 'tora' failed
make: *** [tora] Error 2
```

**Comment by ibre5041** [comment]
There were some includes missing. Try it now.

**Comment by nydn** [comment]
Yes, patch works. Compiles and runs without any error!

**Comment by ibre5041** [comment]
ok, I'm closing it.
