### ISSUE TITLE
Tora3 tuning tab

### ISSUE THREAD

**Issue by pronyma2097** [tora-tool/tora#38]
Hello everyone.

First please forgive my bad english, i'm just a french dba.

I use the tuning section frequently (i got tora 2.1.3) and i figured this section has disappeared in tora 3.
I saw in sources that it was tagged "obsolete", is there any plans on making it working again ?

Thank you.

**Comment by ibre5041** [comment]
I'm going to implement it. This part is still QT3 compliant, and is hard to port QT4/QT5.
