### ISSUE TITLE
Tora should be compilable without oracle libs

### ISSUE THREAD

**Issue by benapetr** [tora-tool/tora#4]
Since it can be used as mysql / postgre tool as well. Right now it's possible to configure it without oracle libs, but it later fail:

In file included from /home/petanb/Documents/tora/src/core/tolistviewformattersql.cpp:47:0:
/home/petanb/Documents/tora/src/connection/tooraclesetting.h:42:34: fatal error: ui_tooraclesettingui.h: No such file or directory

Not requiring these libs would also make it easier to integrate with travis which probably wouldn't allow installation of oracle libraries as they aren't open source

**Comment by ibre5041** [comment]
Tora config properities have to be reviewed. The tab with Oracle settings contains an option(ConfDateFormat) which is used globally - by tolistviewformattersql.cpp. If this option is not Oracle specific it should be moved into other config tab.

This problem relates to a missing feature. At this moment we can not convert a value stored in toQValue back into SQL string literal. To be used in generated SQL quiery.

1st toQValue does not remember original value's datatype withdrawn from a database. 
2nd this needs to be db vendor specific(i.e. at least partially implemented in connection provider).1

**Comment by ibre5041** [comment]
Fixed by fcdcb307cd7d37c40693edf8c488daa6ce4f9fc1. Although this does not make to much sense ATM. Only Oracle port is supported now.
