### ISSUE TITLE
License file grammer .g

### ISSUE THREAD

**Issue by balahsen** [tora-tool/tora#40]
Hello,

Some grammar files .g located in extlibs\parsing.cpp, like MySQLGuiLexer, MySQLLexer or PostgreSQLGuiLexer, have not a license term in the header.
What about the license of these files please?

**Comment by ibre5041** [comment]
I'm not sure. Do yo want to use them? I'm quite sure I did not delete original header from them.
There are various grammars on the internet. I just took one and did modify it.
AFAIK MySQL Worbench has the most complete one, for MySQL. I just decided, that I need two grammars. One for code analysis, the other one for syntax highlighting in in Scintialla editor component.

**Comment by balahsen** [comment]
fyi

Lahsen.

**Comment by ibre5041** [comment]
Not an issue, bug nor a feature request.
