### ISSUE TITLE
TOra3 release still tails to build with Qt4 GUI

### ISSUE THREAD

**Issue by ssten** [tora-tool/tora#42]
Latest (today's) snapshot build error message:

> In file included from /var/tmp/portage/dev-db/tora-9999/work/tora-master/src/widgets/totreewidget.h:38:0,
>                 from /var/tmp/portage/dev-db/tora-9999/work/tora-master/src/tools/toresultview.h:42,
>                 from /var/tmp/portage/dev-db/tora-9999/work/tora-master/src/core/tolistviewformatterxlsx.cpp:43:
>/var/tmp/portage/dev-db/tora-9999/work/tora-master/src/core/tolistviewformatterxlsx.cpp: In member function ‘virtual QString toListViewFormatterXLSX::getFormattedString(toExportSettings&, const QAbstractItemModel*)’:
>/var/tmp/portage/dev-db/tora-9999/work/tora-master/src/core/utils.h:61:27: error: ‘escape’ is not a member of ‘Qt’
> \#define TO_ESCAPE(string) Qt::escape(string)
>                           ^
>/var/tmp/portage/dev-db/tora-9999/work/tora-master/src/core/tolistviewformatterxlsx.cpp:113:25: note: in expansion of macro ‘TO_ESCAPE’
>                 value = TO_ESCAPE(data.toString().toHtmlEscaped());
>                         ^
>/var/tmp/portage/dev-db/tora-9999/work/tora-master/src/core/tolistviewformatterxlsx.cpp:113:51: error: ‘class QString’ has no member named ‘toHtmlEscaped’
>                 value = TO_ESCAPE(data.toString().toHtmlEscaped());
>                                                   ^
>/var/tmp/portage/dev-db/tora-9999/work/tora-master/src/core/utils.h:61:38: note: in definition of macro ‘TO_ESCAPE’
> \#define TO_ESCAPE(string) Qt::escape(string)
>                                      ^
>/var/tmp/portage/dev-db/tora-9999/work/tora-master/src/core/tolistviewformatterxlsx.cpp: At global scope:
> /var/tmp/portage/dev-db/tora-9999/work/tora-master/src/core/tolistviewformatterxlsx.cpp:51:16: warning: ‘{anonymous}::registered’ defined but not used [-Wunused-variable]
>     const bool registered = >toListViewFormatterFactory::Instance().Register(toListViewFormatterIdentifier::XLSX, 
>                ^
> src/CMakeFiles/tora.dir/build.make:6190: recipe for target 'src/CMakeFiles/tora.dir/core/tolistviewformatterxlsx.cpp.o' failed

**Comment by ssten** [comment]
Latest snapshot.
Build fails on the same place with the same error.

amd64
sys-devel/gcc-4.9.3
sys-libs/glibc-2.22-r4

**Comment by ibre5041** [comment]
I can not fail on the same place with the same error. The failing line 113:
`
value = TO_ESCAPE(data.toString().toHtmlEscaped());`

was changed to
`
value = TO_ESCAPE(data.toString());`

**Comment by ssten** [comment]
Today's check with 19 July's snapshot:

[ 72%] Building CXX object src/CMakeFiles/tora.dir/core/tolistviewformatterxlsx.cpp.o
cd /var/tmp/portage/dev-db/tora-3.0.0_pre20160719/work/tora-3.0.0_pre20160719_build/src && /usr/bin/x86_64-pc-linux-gnu-g++  -DNDEBUG -DORACLE_OCI_VER_11G -DPROVIDERS_PATH=\"/usr/lib64/tora-3.0\" -DQT_CORE_LIB -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_NO_DEBUG -DQT_NO_DEBUG_OUTPUT -DQT_SQL_LIB -DQT_THREAD_LIB -DQT_WEBKIT_LIB -DQT_XML_LIB -DSHARE_DIR=\"/usr/share/tora-3.0\" -DTOBUILDTYPE_RELEASE=1 -DTROTL_DLL -DTSQLPARSER_DLL -Dtora_EXPORTS   -DNDEBUG -Wall -std=c++11 -ggdb3 -I/var/tmp/portage/dev-db/tora-3.0.0_pre20160719/work/tora-3.0.0_pre20160719_build/src -I/var/tmp/portage/dev-db/tora-3.0.0_pre20160719/work/tora-master/src -I/usr/include/FerrisLoki -I/var/tmp/portage/dev-db/tora-3.0.0_pre20160719/work/tora-master/extlibs/loki-extra/include -isystem /usr/include/qt4 -isystem /usr/include/qt4/QtWebKit -isystem /usr/include/qt4/QtGui -isystem /usr/include/qt4/QtXml -isystem /usr/include/qt4/QtSql -isystem /usr/include/qt4/QtNetwork -isystem /usr/include/qt4/QtCore -I/var/tmp/portage/dev-db/tora-3.0.0_pre20160719/work/tora-master -I/var/tmp/portage/dev-db/tora-3.0.0_pre20160719/work/tora-master/src/precompiled -I/var/tmp/portage/dev-db/tora-3.0.0_pre20160719/work/tora-3.0.0_pre20160719_build -I/var/tmp/portage/dev-db/tora-3.0.0_pre20160719/work/tora-master/extlibs/trotl/src -I/var/tmp/portage/dev-db/tora-3.0.0_pre20160719/work/tora-master/extlibs/libermodel -I/var/tmp/portage/dev-db/tora-3.0.0_pre20160719/work/tora-master/extlibs/libantlr3cpp-3.5.3/include -I/usr/include/qt4/QtScriptTools -I/usr/include/qt4/QtDBus -I/usr/include/qt4/QtOpenGL -I/usr/include/qt4/QtXmlPatterns -I/usr/include/qt4/QtScript -I/usr/include/qt4/Qt3Support -I/usr/share/qt4/mkspecs/default -I/usr/lib64/oracle/11.2.0.4/client/rdbms/public -I/usr/include/qt4/Qsci    -DQT -DSCI_LEXER -o CMakeFiles/tora.dir/core/tolistviewformatterxlsx.cpp.o -c /var/tmp/portage/dev-db/tora-3.0.0_pre20160719/work/tora-master/src/core/tolistviewformatterxlsx.cpp
In file included from /var/tmp/portage/dev-db/tora-3.0.0_pre20160719/work/tora-master/src/widgets/totreewidget.h:38:0,
                 from /var/tmp/portage/dev-db/tora-3.0.0_pre20160719/work/tora-master/src/tools/toresultview.h:42,
                 from /var/tmp/portage/dev-db/tora-3.0.0_pre20160719/work/tora-master/src/core/tolistviewformatterxlsx.cpp:43:
/var/tmp/portage/dev-db/tora-3.0.0_pre20160719/work/tora-master/src/core/tolistviewformatterxlsx.cpp: In member function ‘virtual QString toListViewFormatterXLSX::getFormattedString(toExportSettings&, const QAbstractItemModel\*)’:
/var/tmp/portage/dev-db/tora-3.0.0_pre20160719/work/tora-master/src/core/utils.h:61:27: error: ‘escape’ is not a member of ‘Qt’
 \#define TO_ESCAPE(string) Qt::escape(string)
                           ^
/var/tmp/portage/dev-db/tora-3.0.0_pre20160719/work/tora-master/src/core/tolistviewformatterxlsx.cpp:113:25: note: in expansion of macro ‘TO_ESCAPE’
                 value = TO_ESCAPE(data.toString());
                         ^
/var/tmp/portage/dev-db/tora-3.0.0_pre20160719/work/tora-master/src/core/tolistviewformatterxlsx.cpp: At global scope:
/var/tmp/portage/dev-db/tora-3.0.0_pre20160719/work/tora-master/src/core/tolistviewformatterxlsx.cpp:51:16: warning: ‘{anonymous}::registered’ defined but not used [-Wunused-variable]
     const bool registered = toListViewFormatterFactory::Instance().Register(toListViewFormatterIdentifier::XLSX, createXLSX);
                ^
src/CMakeFiles/tora.dir/build.make:6190: recipe for target 'src/CMakeFiles/tora.dir/core/tolistviewformatterxlsx.cpp.o' failed
make[2]: *** [src/CMakeFiles/tora.dir/core/tolistviewformatterxlsx.cpp.o] Error 1

**Comment by ibre5041** [comment]
try to add:
`#include <Qt>`
into src/core/utils.h

It look like your Qt4 version does not include it implicitly.

**Comment by ssten** [comment]
Adding:

> \#include "core/tora_export.h"
>
> \#include \<Qt\>
> \#include \<QtCore/QAtomicInt\>

Not fixed this issue.

I use stable Qt4:
dev-qt/qtcore (4.8.6-r2(4) and others dependent.

**Comment by ibre5041** [comment]
Then I do not know. The function escape() is member of Qt namespace.

[QString Qt::escape(const QString & plain)](http://doc.qt.io/qt-4.8/qt.html#escape)

Try to replace the line:
`value = TO_ESCAPE(data.toString());`

with
`value = ::Qt:escape(data.toString());`

This is was that macro should do.

**Comment by ssten** [comment]
I also don't know why.

The last error was:

> /var/tmp/portage/dev-db/tora-3.0.0_pre20160719/work/tora-master/src/core/tolistviewformatterxlsx.cpp: In member function ‘virtual QString toListViewFormatterXLSX::getFormattedString(toExportSettings&, const QAbstractItemModel\*)’:
> /var/tmp/portage/dev-db/tora-3.0.0_pre20160719/work/tora-master/src/core/tolistviewformatterxlsx.cpp:113:26: error: ‘escape’ is not a member of ‘Qt’
                  value = ::Qt::escape(data.toString());
                          ^
>/var/tmp/portage/dev-db/tora-3.0.0_pre20160719/work/tora-master/src/core/tolistviewformatterxlsx.cpp: At global scope:
> /var/tmp/portage/dev-db/tora-3.0.0_pre20160719/work/tora-master/src/core/tolistviewformatterxlsx.cpp:51:16: warning: ‘{anonymous}::registered’ defined but not used [-Wunused-variable]
>     const bool registered = > toListViewFormatterFactory::Instance().Register(toListViewFormatterIdentifier::XLSX, createXLSX);
>                ^
> src/CMakeFiles/tora.dir/build.make:6190: recipe for target 'src/CMakeFiles/tora.dir/core/tolistviewformatterxlsx.cpp.o' failed

Possibly missed include (where?).
