### ISSUE TITLE
Windows7 64Bit Oracle Libraries Loading Error

### ISSUE THREAD

**Issue by lomatus** [tora-tool/tora#43]
Hello All,

I just download Tora.3.0.96.Release.64bit  from sf.net, it can't load Oracle Driver when start up.
I've installed Oracle 11.2.0.3.0 64Bit Client

What exactly version of oracle client should Tora work with. Thanks

Eg. Oracle 11gR2 64 or Oracle 12c 64 or 32bit.

Thanks!

**Comment by lomatus** [comment]
Screenshot:
[<a href="http://www.freeimagehosting.net/commercial-photography/california/palm-springs/"><img src="http://i.imgur.com/QSbCX7p.png" alt="Palm Springs commercial photography"></a>](url)

**Comment by ibre5041** [comment]
The client definitely should be 64bit one. Instant one or Thick one. In case of Thick one you should have $ORACLE_HOME/bin set in your PATH. Try to download an Instant one and then set ORACLE_HOME in Tora's preferences. Do you have multiple Oracle clients installed?

**Comment by lomatus** [comment]
Only one Oracle client installed, 64Bit 11gR2
When add BIN to PATH Environment,  another error show up as screenshot.
[<a href="http://www.freeimagehosting.net/commercial-photography/california/palm-springs/"><img src="http://i.imgur.com/ljBiSBb.png" alt="Palm Springs commercial photography"></a>](url)

**Comment by ibre5041** [comment]
I have to check it. Did you try to use Instant client?

**Comment by lomatus** [comment]
Hello, ibre
Thanks for your kindness assistance, it works with full version of oracle client 11gR2 now.
You can close this issue now.
