### ISSUE TITLE
Tora always open about page

### ISSUE THREAD

**Issue by mmm286** [tora-tool/tora#46]
Hi
I downloaded Tora but when I open the application always shows me the about page
Could you help me?
Thanks and sorry for my English

**Comment by ibre5041** [comment]
What version you use? 
What is in your registry key: HKEY_CURRENT_USER\Software\TOra\TOra3\preferences\Main\LastVersion ?

There should be "3.0". And the About dialog should only pop-up when this registry value differs from actual one.

**Comment by ibre5041** [comment]
no resplonse.
