### ISSUE TITLE
fail to build with legacy (Qt4) GUI

### ISSUE THREAD

**Issue by ssten** [tora-tool/tora#49]
Some new details following issue #42 
Attemp to build TOra3 with Qt4 GUI still fails.

The error message is:

> /var/tmp/portage/dev-db/tora-9999/work/tora-master/src/core/tolistviewformatterxlsx.cpp: In member function ‘virtual QString toListViewFormatterXLSX::getFormattedString(toExportSettings&, const QAbstractItemModel*)’:
> /var/tmp/portage/dev-db/tora-9999/work/tora-master/src/core/utils.h:61:27: error: ‘escape’ is not a member of ‘Qt’
>  #define TO_ESCAPE(string) Qt::escape(string)

On My system together with Qt4 installed I have Qt5 installed.
Following https://wiki.qt.io/Transition_from_Qt_4.x_to_Qt5#Qt::escape_is_deprecated I can guess, that somewhere build system uses autodetected Qt5 ignoring QT5_BUILD=OFF.

Complete build log is available from https://paste.pound-python.org/show/L6TJ3lcN9SfMCCoijrYb/

**Comment by ibre5041** [comment]
Try to add "-M"  compiler FLAG (or just -MM) into top level CMakeList.txt to report header files used during compilation.

**Comment by ssten** [comment]
Doing so (adding -MM into CMAKE_C_FLAGS* variables in top-level CMakeLists.txt) breaks Oracle detection:

> CMake Error at cmake/modules/FindOracle.cmake:124 (IF):
>  if given arguments:
>
>    "GREATER" "120"
>
>  Unknown arguments specified
>Call Stack (most recent call first):
>  CMakeLists.txt:279 (FIND_PACKAGE)

Although for now I try to build TOra3 woth 11.2.0.4 client.

**Comment by ibre5041** [comment]
Is this still a problem? I'm about to drop support for Qt4. Are there any users, who use Tora with Qt4?

**Comment by ssten** [comment]
At least in Gentoo GNU/Linux QT5 version can't be commited because of [blocker bug #541604](https://bugs.gentoo.org/show_bug.cgi?id=541604).

**Comment by ibre5041** [comment]
So to root case is, there is no qscintilla for Qt5 on Gentoo? How is this solved by other projects?
BTW: you can build Tora with "internal" version of qscintilla(statically linked), it is mostly used for Windows builds.

**Comment by ssten** [comment]
There is no yet proper build of x11-libs/qscintilla:5 in Gentoo.

I remember about bundled versions, but prefer to use OpenSource standard (system libraries).

**Comment by ibre5041** [comment]
What about using internal qscintilla like it is done in sqlliteman? It looks like the whole story is not over yet. The bug is closed, but the pull request is not merged yet - https://github.com/gentoo/gentoo/pull/3188.

**Comment by ibre5041** [comment]
support for Qt4 will be dropped
