### ISSUE TITLE
Unable to connect to ODBC on Windows

### ISSUE THREAD

**Issue by Choens** [tora-tool/tora#50]
Using Tora 3.0 on Windows 7 downloaded from SourceForge. I've never compiled a QT app on Windows before, but if someone can help walk me through it, I'll try . . . if people here believe that is likely to help my issue. Or, if I am doing something terribly ignorant, feel free to correct me. 

## Setup:

- I have a ODBC DSN called "hpdw" on my PC. See below for a (slightly) modified version of the config   window.
- I get this same error when using my Oracle DSNs. I am focused on the Vertica error, because there is no other way to connect to Vertica using Tora. With Oracle, I can use the Oracle client.
- I am able to successfully use this DSN to connect to Vertica using R, SAS, etc. I use it nearly every day. I know this is a valid DSN.
- See below for screenshot.

![image](https://cloud.githubusercontent.com/assets/424993/20141878/5dfbb854-a660-11e6-90bf-b9ba92970b2b.png)

## Error:

When I attempt to use it from within Tora, I get an error (see below for screenshot):

    Error: Unable to connect to the database.
    02: Tried to get unknown SQL (toQSqlConnection:Version)

![image](https://cloud.githubusercontent.com/assets/424993/20141946/b9a19638-a660-11e6-83e0-b67d2c59d54c.png)

I am open to play around with this. I've got other ways to connect to Vertica. I'd like to evaluate Tora, but I'm in no rush.

**Comment by ibre5041** [comment]
Fixed.

**Comment by ibre5041** [comment]
Fixed in trunk.

**Comment by Choens** [comment]
Thank you.
