### ISSUE TITLE
Copy in Format carries over "#" in column even when line numbers option unchecked

### ISSUE THREAD

**Issue by aizenmyou** [tora-tool/tora#52]
Version: v3.0alpha-58-g1bc5385-dirty

When you right click _Copy in format_ and leave _Include Row Numbers_ **unchecked**, it still creates an extra column header named "#" even with no line numbers present.

**Comment by aizenmyou** [comment]
The issue is also present in the newer BUILD_TAG: v3.1alpha-89-Release-g4e9fd58 (Windows 64bit)

**Comment by ibre5041** [comment]
I somehow could not reproduce. Try never version Tora.3.1alpha.94.Release.64bit.msi.

**Comment by aizenmyou** [comment]
Same issue running BUILD_TAG: v3.1-1-Release-gfd9e951 (2017/01/06 build date)

These are what I have sepected:
![image](https://cloud.githubusercontent.com/assets/4256716/21857862/9a4ed33c-d7ec-11e6-921a-8c3334585561.png)

This is what the output ends up. Note that the 66713 should be under the COUNT(CUSTNO) column.
![image](https://cloud.githubusercontent.com/assets/4256716/21857948/e6f092de-d7ec-11e6-9d5a-772dceeec93c.png)

**Comment by ibre5041** [comment]
Oh I see. The clipboard contains different mime types. So the plaintext content is OK, while .xlsx (the Excel xml format) is wrong. I will look at it.

**Comment by ibre5041** [comment]
The problem must be here:

https://github.com/tora-tool/tora/blob/master/src/core/tolistviewformatterxlsx.cpp#L58

**Comment by ibre5041** [comment]
ok fixed. TabDelim and HTML formats were fixed.
