### ISSUE TITLE
v3.1 is still showing v3.0

### ISSUE THREAD

**Issue by peterhoeg** [tora-tool/tora#53]
I'm guessing this is the culprit:
https://github.com/tora-tool/tora/blob/master/CMakeLists.txt#L73

**Comment by ibre5041** [comment]
Ok fixed, btw do you compile the application by your onw? Without git?

**Comment by peterhoeg** [comment]
I'm packaging tora for NixOS: https://github.com/NixOS/nixpkgs/pull/21635

The fetcher on NixOS downloads a tarball from github instead of doing a checkout.

Any chance I could talk you into doing a 3.1.1 with the version fixed? I will then update the NixOS definition accordingly.

**Comment by ibre5041** [comment]
The version 3.1-1 means one commit after the tag v.3.1 was created. Where do you get tarballs from? The current master trunk is version 3.1-6 (according to git). I would have to delete the tag, rebase the git repository and then create the tag 3.1 again.

**Comment by peterhoeg** [comment]
Actually I meant 3.1 but with the version fixed to 3.1.1 and released as "v3.1.1" without any rebasing.

In NixOS the function responsible for fetching from github pulls the tarballs directly from the github:

https://github.com/tora-tool/tora/archive/v3.1.tar.gz

**Comment by ibre5041** [comment]
ok closed - and re-tagged.
