### ISSUE TITLE
tora fails to detect x11-libs/qscintilla[qt5]

### ISSUE THREAD

**Issue by ssten** [tora-tool/tora#54]
Build attemp of fresh (yesterday's) snapshot fails on detection of qscintilla library.

System's package installs the following library files:

=x11-libs/qscintilla-2.9.4:
…
/usr/lib64/libqscintilla2.so.12.0.2
/usr/lib64/libqscintilla2.so
/usr/lib64/libqscintilla2.so.12
/usr/lib64/libqscintilla2.so.12.0

The following simple patch fixes it:

tora-qscintilla.patch:
diff -Naur tora-master.orig/cmake/modules/FindQScintilla.cmake tora-master/cmake/modules/FindQScintilla.cmake
--- tora-master.orig/cmake/modules/FindQScintilla.cmake	2017-01-24 13:25:31.000000000 +0300
+++ tora-master/cmake/modules/FindQScintilla.cmake	2017-01-24 13:26:19.000000000 +0300
@@ -84,7 +84,7 @@
     SET(LIBRARYPATH ${QT5_WIDGETSLIBRARYPATH} "/usr/lib/" "/usr/local/lib")
     MESSAGE("QScintilla2 LIBPATH \"${LIBRARYPATH}\"")
 
\-    FIND_LIBRARY(QSCINTILLA_LIBRARY NAMES qscintilla2-qt5 qt5scintilla2 libqscintilla2.a qscintilla2.lib PATHS ${LIBRARYPATH})
\+    FIND_LIBRARY(QSCINTILLA_LIBRARY NAMES qscintilla2-qt5 qt5scintilla2 libqscintilla2.so qscintilla2.lib PATHS ${LIBRARYPATH})
 
     # Check
     IF(QSCINTILLA_LIBRARY)

**Comment by msva** [comment]
fix for explaination:
1) QScintila in Gentoo does not install static library (I don't know the reason, though)
2) FindQScintilla module does not search for dynamic version of the library with the same name as it search static to be.

So, dear devs, can you fix this issue?

**Comment by ibre5041** [comment]
Is there a way how to patch it only for gentoo? On Ubuntu libqscintilla2.so is qscintilla library depending on Qt4, while libqt5scintilla2.so is for Qt5. If I "fix" it I will break support to Ubuntu/Debian/Fedora.

```
        # ldd /usr/lib/libqscintilla2.so
	linux-vdso.so.1 =>  (0x00007fff021ad000)
	libQtGui.so.4 => /usr/lib/x86_64-linux-gnu/libQtGui.so.4 (0x00007fec0f501000)
	libQtCore.so.4 => /usr/lib/x86_64-linux-gnu/libQtCore.so.4 (0x00007fec0f00e000)
        ...
        # ldd /usr/lib/libqt5scintilla2.so 
	linux-vdso.so.1 =>  (0x00007ffc98bb8000)
	libQt5PrintSupport.so.5 => /usr/lib/x86_64-linux-gnu/libQt5PrintSupport.so.5 (0x00007f4566e01000)
	libQt5Widgets.so.5 => /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5 (0x00007f4566774000)
        ...
```

The file with .a suffix if "only" for case, when internal embedded library is used.

**Comment by msva** [comment]
> Is there a way how to patch it only for gentoo?
Actually, Gentoo defines `-DCMAKE_BUILD_TYPE=Gentoo`, so,  I guess, it is 
possible to take that into account, but I'm not sure if it is safe to rely on 
it's persistence.

> On Ubuntu libqscintilla2.so
Somewhy, Gentoo maintainers made qscintilla package to mutually exclusive 
support either Qt4 or Qt5 with same SONAMEs.
// I guess. I don't want to install Qt4 just to check SONAMEs.

**Comment by ibre5041** [comment]
The problem is, that when I allow library libqscintilla2.so to be detected, tora (Qt5 build) will link against libqscintilla2.so (Qt4 build) and it will work somehow. But it will crash randomly due to slightly different ABI. Or at least I recall I had these issues in the past.

**Comment by ibre5041** [comment]
Try it now.

**Comment by msva** [comment]
В письме от понедельник, 6 февраля 2017 г. 13:58:37 +07 пользователь Ivan 
Brezina написал:
> The problem is, that when I allow library libqscintilla2.so to be detected,
> tora (Qt5 build) will link against libqscintilla2.so (Qt4 build) and it
> will work somehow. But it will crash randomly due to slightly different
> ABI. Or at least I recall I had these issues in the past.

I guess, it will be safe to check for BUILD_TYPE=Gentoo, and append 
`libqscintilla2.so` unrelated to which Qt version is used (as I said above, 
QScintilla in Gentoo can be build against only on of them, but not both, and I 
making tora ebuild to require QScintilla to be built against same Qt version 
as user selected for tora).

**Comment by msva** [comment]
> Try it now.
```
-- Found QScintilla2: /usr/lib64/libqscintilla2.so
--          includes: /usr/include/qt5/Qsci
QScintilla2 Found OK
```

**Comment by ibre5041** [comment]
Never mind. I'm going to drop support for Qt4 soon.

**Comment by ssten** [comment]
AFAIR after switching to Qt5 default Qt4 build was constantly broken.
At least in Gentoo.
