### ISSUE TITLE
Build failure with Qt built with -reduce-relocations

### ISSUE THREAD

**Issue by ssten** [tora-tool/tora#55]
Trying to build yesterday's snapshot with =dev-qt/qtcore-5.6.2-r1 I've got the following error:

[  1%] Building CXX object extlibs/libermodel/CMakeFiles/ermodel.dir/canvasedge.cpp.o
cd /var/tmp/portage/dev-db/tora-3.0.0_pre20170124/work/tora-3.0.0_pre20170124_build/extlibs/libermodel && /usr/bin/x86_64-pc-linux-gnu-g++  -DNDEBUG -DORACLE_OCI_VER_11G -DQT_CORE_LIB -DQT_GUI_LIB -DQT_NO_DEBUG -DQT_NO_DEBUG_OUTPUT -DQT_THREAD_LIB -DTOBUILDTYPE_RELEASE=1 -I/var/tmp/portage/dev-db/tora-3.0.0_pre20170124/work/tora-3.0.0_pre20170124_build/extlibs/libermodel -I/var/tmp/portage/dev-db/tora-3.0.0_pre20170124/work/tora-master/extlibs/libermodel -I/FerrisLoki -I/var/tmp/portage/dev-db/tora-3.0.0_pre20170124/work/tora-master/extlibs/loki-extra/include -I/usr/include/qt5 -I/usr/include/qt5/QtCore -I/usr/lib64/qt5/mkspecs/linux-g++ -I/usr/include/qt5/QtGui -I/usr/include/qt5/QtNetwork -I/usr/include/qt5/QtPrintSupport -I/usr/include/qt5/QtWidgets -I/usr/include/qt5/QtSql -I/usr/include/qt5/QtXml   -DNDEBUG -Wall -std=c++11 -ggdb3      -DQT -DSCI_LEXER -o CMakeFiles/ermodel.dir/canvasedge.cpp.o -c /var/tmp/portage/dev-db/tora-3.0.0_pre20170124/work/tora-master/extlibs/libermodel/canvasedge.cpp
In file included from /usr/include/qt5/QtWidgets/qgraphicsitem.h:37:0,
                 from /usr/include/qt5/QtWidgets/QAbstractGraphicsShapeItem:1,
                 from /var/tmp/portage/dev-db/tora-3.0.0_pre20170124/work/tora-master/extlibs/libermodel/canvaselement.h:26,
                 from /var/tmp/portage/dev-db/tora-3.0.0_pre20170124/work/tora-master/extlibs/libermodel/canvaselement.cpp:20:
/usr/include/qt5/QtCore/qglobal.h:1087:4: error: #error "You must build your code with position independent code if Qt was built with -reduce-relocations. " "Compile your code with -fPIC (-fPIE is not enough)."
 \#  error "You must build your code with position independent code if Qt was built with -reduce-relocations. "\
    ^
In file included from /usr/include/qt5/QtCore/qnamespace.h:37:0,
                 from /usr/include/qt5/QtCore/qobjectdefs.h:41,
                 from /usr/include/qt5/QtCore/qobject.h:40,
                 from /usr/include/qt5/QtWidgets/qgraphicsscene.h:37,
                 from /usr/include/qt5/QtWidgets/QGraphicsScene:1,
                 from /var/tmp/portage/dev-db/tora-3.0.0_pre20170124/work/tora-master/extlibs/libermodel/canvasedge.h:31,
                 from /var/tmp/portage/dev-db/tora-3.0.0_pre20170124/work/tora-master/extlibs/libermodel/canvasedge.cpp:28:
/usr/include/qt5/QtCore/qglobal.h:1087:4: error: #error "You must build your code with position independent code if Qt was built with -reduce-relocations. " "Compile your code with -fPIC (-fPIE is not enough)."
 \#  error "You must build your code with position independent code if Qt was built with -reduce-relocations. "\

**Comment by ibre5041** [comment]
does it mean that the issue with qscintilla2 on gentoo was fixed?

**Comment by msva** [comment]
@ibre5041 yes, it is fixed (it is QScintilla[qt5] in the tree now)

**Comment by msva** [comment]
and, talking on topic of the issue, I am getting the same too, and have no idea about how to fix this... exporting `-fPIC -DPIC` to cflags doesn't help :(

**Comment by msva** [comment]
update: sed'ing `-ggdb3` to `-ggdb3 -fPIC` in `CMakeLists.txt` аfixed the problem.

**Comment by ibre5041** [comment]
This is really turning into a nigtmare. I fixed it already several times. But I do not recall details.
It depends on cmake version. Some versions embed value of CMAKE_CXX_FLAGS_RELEASE in CMAKE_CXX_FLAGS - while others do not. 

Some Qt versions set Qt5_POSITION_INDEPENDENT_CODE, therefore I tried to use CMAKE_POSITION_INDEPENDENT_CODE.

```
  # prevent error "You must build your code with position independent code if Qt was built with..
  #if (Qt5_POSITION_INDEPENDENT_CODE)
  #  SET(CMAKE_POSITION_INDEPENDENT_CODE ON)
  #endif()

```

But it was not supported on older cmake version. So I decided to use Qt5Widgets_EXECUTABLE_COMPILE_FLAGS. Theoretically this variable should contain flags, Qt was built with. Can you please check wheter your Qt installation sets this variable in .cmake files?

**Comment by ibre5041** [comment]
So this:

```
  SET(CMAKE_CXX_FLAGS         "${CMAKE_CXX_FLAGS} ${Qt5Widgets_EXECUTABLE_COMPILE_FLAGS}")
  SET(CMAKE_C_FLAGS           "${CMAKE_C_FLAGS}   ${Qt5Widgets_EXECUTABLE_COMPILE_FLAGS}")
  STRING(TOUPPER "CMAKE_CXX_FLAGS_${CMAKE_BUILD_TYPE}" _flags_var_name)
  SET(${_flags_var_name}      "${${_flags_var_name}} ${Qt5Widgets_EXECUTABLE_COMPILE_FLAGS}")
  SET("CMAKE_CXX_FLAGS_${CMAKE_BUILD_TYPE}" _flags_var_name)
```

Should add the proper flags to the current build type.

**Comment by msva** [comment]
Not sure about `Widgets` one:
```make
$ grep -r COMPILE_FL /usr/lib64/cmake/Qt5Widgets/
/usr/lib64/cmake/Qt5Widgets/Qt5WidgetsConfig.cmake:    set(Qt5Widgets_EXECUTABLE_COMPILE_FLAGS "")
/usr/lib64/cmake/Qt5Widgets/Qt5WidgetsConfig.cmake:        list(APPEND Qt5Widgets_EXECUTABLE_COMPILE_FLAGS ${Qt5${_module_dep}_EXECUTABLE_COMPILE_FLAGS})
/usr/lib64/cmake/Qt5Widgets/Qt5WidgetsConfig.cmake:    list(REMOVE_DUPLICATES Qt5Widgets_EXECUTABLE_COMPILE_FLAGS)
```

But `Core` one seems to do the right thing:
```make
/usr/lib64/cmake/Qt5Core/Qt5CoreConfigExtras.cmake:    set(Qt5Core_EXECUTABLE_COMPILE_FLAGS "-fPIC")
```

**Comment by msva** [comment]
And, by the way, why do you just not add `-fPIC` as is by default to C{,XX}FLAGS unrelated to how Qt is built? :)

**Comment by ibre5041** [comment]
because some distros need -fPIE and some other need even more flags. You should really use the same flags Qt was built with.

**Comment by ibre5041** [comment]
Try it now.

**Comment by msva** [comment]
> Try it now.

Looks like working fine.
Although, wouldn't it brake compatibility with older cmakes, like you said 
before? :)
