### ISSUE TITLE
On Ubuntu 16.10 opening schema browser triggers assert failure

### ISSUE THREAD

**Issue by mmcfts** [tora-tool/tora#56]
Hi,
I cloned the repository, installed all the dependencies and compiled tora, installed and ran the executable, all went well, I connected to Postgres, ran a query, got some results back, then I clicked on the schema browser, and there the software stopped on an assertion failure.
So I checked out the 3.0.100 version, compiled it, ran it, and again it crashed.
So I looked for a recent ubuntu build, found the 3.0.100 version compiled by Ivan, installed it, and again it crashed on the same assertion, so here is Ivan's build assertion failure on my Ubuntu 16.10:
mauro@kmer:~/git/tora$ /usr/bin/tora
QObject::connect: No such slot toMain::addConnection(toConnection *conn, bool) in /home/ivan/devel/tora-project/src/main/tomain.cpp:148

(tora:6677): Gtk-WARNING **: Theme directory  imported-Humanity/192 of theme Lubuntu has no size field

WARNING:  there is no transaction in progress
QObject::connect: No such slot toWorksheet::slotChangeRefresh(const QString &) in /home/ivan/devel/tora-project/src/tools/toworksheet.cpp:370
QObject::connect:  (sender name:   'toRefreshCombo')
QObject::connect:  (receiver name: 'toWorksheet')
QObject::connect: No such slot toResultPlanView::slotStop() in /home/ivan/devel/tora-project/src/tools/toresultplan.cpp:110
WARNING:  there is no transaction in progress
QObject::connect: No such slot toResultDrawing::refreshAction() in /home/ivan/devel/tora-project/src/tools/toresultdrawing.cpp:167
QObject::connect: Cannot connect DotGraphView::removeEdge(const QString&) to (null)::removeEdge(const QString&)
QObject::connect: Cannot connect DotGraphView::removeNodeNamed(const QString&) to (null)::removeNodeNamed(const QString&)
QObject::connect: Cannot connect DotGraphView::removeElement(const QString&) to (null)::removeElement(const QString&)
ASSERT failure in toconfiguration.cpp:79	QVariant toConfigurationNew::option(int): "Unknown enum: 5014", file /home/ivan/devel/tora-project/src/core/toconfiguration.cpp, line 79
Aborted
mauro@kmer:~/git/tora$ file /usr/bin/tora
/usr/bin/tora: ELF 64-bit LSB executable, x86-64, version 1 (GNU/Linux), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, for GNU/Linux 2.6.32, BuildID[sha1]=aa8d0d9d37ad8156ad71703aecb35acb371802fb, stripped
Any clue?

**Comment by ibre5041** [comment]
Try to compile the application with Oracle support. The enum value IncludePromptBool is defined in tooracleconfiguration.h. This one is not included when Oracle is not detected. I have to move these generic config options out of ToConfiguration::Oracle namespace.

**Comment by mmcfts** [comment]
Ok, it works if compiled with Oracle support. The browser now opens up, but :) there's nothing ... and I get the following error message:
gio gen 26 21:59:28 2017
ERROR:  syntax error at end of input
LINE 1: EXECUTE 
                ^
(42601)
Query not active

Looking at the code I understand that the schema browser for PostgreSQL is unfinished.
I use Tora on Windows at work with Oracle where it works like a charm. It's fast and easy to use and it has some nice features that other tools don't have.
Wanted to try to fix the "record update bug", but to get there it seems that I need to install and configure an Oracle database at home on my lousy laptop ... sigh, which is faster than trying to make the schema browser work under PostgreSQL I suppose. Thanks for the quick feedback.

**Comment by ibre5041** [comment]
Yes. so far we do not have anybody to support PostgreSQL . I mainly work on Oracle support.
