### ISSUE TITLE
[UI] Hardcoded colors in query editor widget

### ISSUE THREAD

**Issue by msva** [tora-tool/tora#59]
I'm getting a trouble when trying to prepare query using dark system colour scheme: http://i.imgur.com/kpwjcnC.png.
There is hardcoded yellow background of active line (or, at least, I failed to find where to change it in `Preferences`.
And, it seems, font colour (white) is also hardcoded to be same as system default (instead of "Default" defined in `Preferences->Editor Settings->Syntax`)

**Comment by ibre5041** [comment]
Duplicate of #31.

**Comment by msva** [comment]
Ok // although, here it described a bit detailed :)
// and #31 overued it's milestone :)

So, close this issue on your decision.
