### ISSUE TITLE
Schema Browser - searching in Code/Script tab is not allowed

### ISSUE THREAD

**Issue by mkyral** [tora-tool/tora#68]
In Schema Browser I can investigate code of triggers/procedures/packages... But I can't search there.  CTRL+F does nothing. I have to copy the whole text to external editor and use it's search function.

![obrazek](https://cloud.githubusercontent.com/assets/155542/25992699/affa92fa-3707-11e7-87df-36bd8a999da9.png)

Will be possible to enable searching in Code and Script tabs? 

I'm using Tora 3.1 on Gentoo.

```
GITVERSION: v3.1-29-g372cd70-dirty
GITVERSION_MAJOR: 3
GITVERSION_MINOR: 1
GIT_BUILD_TYPE: Release
GITVERSION_COUNT: 29
GITVERSION_SHA1: g372cd70
GITVERSION_SHORT: 3.1
GIT_BRANCH: HEAD
BUILD_TAG: v3.1-29-Release-g372cd70-dirty
BUILD_DATE: 2017-05-03
```

**Comment by ibre5041** [comment]
Should be fixed now. Searching was completely re-designed.
