### ISSUE TITLE
Non-git build — CMake Error: The dependency target "revisiontag" of target "tora" does not exist.

### ISSUE THREAD

**Issue by ssten** [tora-tool/tora#69]
Today trying to build TOra from zipped snapshot, without fetching complete git tree I've got the following error:

> -- Configuring done
> CMake Error at src/CMakeLists.txt:852 (ADD_DEPENDENCIES):
>  The dependency target "revisiontag" of target "tora" does not exist.

Is it possible to build TOra without git binary and fetching complete tree.
If yes, how can I do it?

**Comment by ibre5041** [comment]
grrr, it was possible with lower version of CMAKE. I have to think out a way to generate version number when git is not available. So far version number is generated from git tag.

but frankly speaking this is not mine priority ATM, why do you need it?

**Comment by ssten** [comment]
I want to get git-independent «release» build of TOra in Gentoo.
Because git versions (-9999) are masked and not recommended for ordinar users.

Possibly, the easiest solution will be to make an optional «version» variable, passed by build system?

**Comment by ibre5041** [comment]
ok I've checked it with "cmake version 3.5.1", it reports an error, but makefiles are generated.

**Comment by ibre5041** [comment]
try it now
