### ISSUE TITLE
unsensitive case on table name in schema browser

### ISSUE THREAD

**Issue by ricovdm** [tora-tool/tora#70]
Hello,

With TOra 3.1.1, if a table is created with a mix of uppercase and lowercase characters (create table "IAmATable" ("Nombre" numeric);), no information can be retrieved in the schema browser as shown below :

"
mer. mai 24 17:05:15 2017

ORA-00942: table or view does not exist

error at SQL position 22 [1.23]:
SELECT  t.* FROM test.iamatable t 
                      ^

last SQL statement:
SELECT  t.* FROM test.iamatable t 

mer. mai 24 17:05:15 2017

ORA-00942: table or view does not exist

mer. mai 24 17:08:01 2017
Error in toExtract
Operation:      Create
Object:         TEST.IAMATABLE
Error:          
ORA-31603: object "IAMATABLE" of type TABLE not found in schema "TEST"
ORA-06512: at "SYS.DBMS_METADATA", line 5805
ORA-06512: at "SYS.DBMS_METADATA", line 8344
ORA-06512: at line 1

error at SQL position 0 [1.1]:
SELECT dbms_metadata.get_ddl(:typ           ,
^

last SQL statement:
SELECT dbms_metadata.get_ddl(:typ           ,
                             :nam           ,
                             :sch           ) FROM dual

"

It is a regression because there was no problem with TOra 2.1.3.

KR,

ERA

**Comment by ibre5041** [comment]
fixed in trunk

**Comment by ricovdm** [comment]
Now works perfectly
