### ISSUE TITLE
no autocomplete in version 3.1

### ISSUE THREAD

**Issue by nicholascarroll** [tora-tool/tora#71]
Version 3.1 on Windows, autocomplete is not working at all in sql worksheet. I tried typing a partial table name and then waiting, pressing Ctl T, Ctl Space. Also a table name, a dot and waiting, and tried those keys again. 

Windows 7.

**Comment by ibre5041** [comment]
so far it it works only when you use schema prefix. for example type "select * from hr.j" and press "CTRL+T".

**Comment by ibre5041** [comment]
so far it it works only when you use schema prefix. for example type "select * from hr.j" and press "CTRL+T".

BTW: try version 3.2.

**Comment by nicholascarroll** [comment]
hey great! ctrl T completes table. how to complete columns?

**Comment by nicholascarroll** [comment]
i have installed version 3.2. It still does not complete column, and it seems I have to prefix the schema name to get table completion.

**Comment by ibre5041** [comment]
it is not implemented yet.

**Comment by nicholascarroll** [comment]
If you want users, I suggest you implement autocomplete columns and forget about QueryModel diagrams.
