### ISSUE TITLE
I couldn't see Oracle Instant Client or Oracle(TNS) in "Connection provider" on TOra 3.2.40 64bit

### ISSUE THREAD

**Issue by sahincam** [tora-tool/tora#75]
Hi,
I'm new in TOra.
Because of our company restricted, I could'nt install any program on my computer and I haven't any privilege for change any system variable.

So I download Tora 3.2.40 64.zip and extract It in T:\Tora. Oracle Client 11.2.0 32 bit also installed my computer.
I prepare a Tora.cmd file like this.
set ORACLE_HOME=T:\ORACLE\product\11.2.0\client_1\
set LD_LIBRARY_PATH=%ORACLE_HOME%\LIB
set TNS_ADMIN=%ORACLE_HOME%\network\admin
T:\Tora\Tora.exe

When I run this script, Tora open without any errors, but I couldn't find any oracle client or oracle(TNS) items in "Connection Provider" combobox.

I googled and try many solutions, for example 
All Oracle lib and dll files copied in Tora directory.
I downloaded tora2.1.3-win32.zip, I can see Oracle Client and Oracle(TNS) in connection provider but get different errors.

How can i solve this problem?

BR.
Sahin

**Comment by sahincam** [comment]
Operating system is Windows 7 64 bit Enterprise edition.

**Comment by ibre5041** [comment]
You can change env. variables even without admin privs by executing

> rundll32 sysdm.cpl,EditEnvironmentVariables

but in case of Tora even this should not be necessary. 
Go to Edit -> Preferences -> Global Settings -> ORACLE_HOME
and set path to T:\ORACLE\product\11.2.0\client_1. (or to downloaded Instant client).
Then restart the app.

**Comment by sahincam** [comment]
Hi Ivan,


Thank you for respond.

I think I couldn't explain my problem. I can set environment variable,  and I did, restart app, yes. But still I cant see oracle client in connection provider combobox.


Is there any troubleshooting methot in Tora, for example open log options in order to detect my problem.

Is there and problem  Tora 64 bit and Oracle client 32 bit work togather.



BR

________________________________

**Comment by ibre5041** [comment]
There is no way how to use 32bit client with 64bit Tora. If  you can download portable .zip with Tora you cal also download 64bit .zip archive with Oracle instant client.

PS: debug build of Tora would tell you why oci.dll was not loaded, but in your case it is obvious anyway.
