### ISSUE TITLE
Change in Editor behavior between 3.2.0 and 3.2.33

### ISSUE THREAD

**Issue by jpetersonme** [tora-tool/tora#76]
In 3.2.0 and before I was able to open saved .sql files and it would display them in the editor. I downloaded 3.40 today and installed it and noticed I could not open the same saved .sql file. I uninstalled 3.40 and installed 3.2.33. It also would not display the saved .sql file. Copy and pasting queries from notepad doesn't seem to work either.

I then tried the following binary versions:
Doesn't work as expected:
Tora.3.2.40.Release.64bit.msi
Tora.3.2.33.Release.64bit.msi

Works as expected:
Tora.3.2.0.Release.64bit.msi
Tora.3.1.1.Release.64bit.msi
Tora.3.1alpha.94.Release.64bit.msi
Tora.3.0.100.Release.64bit.msi

Did the default action change between these versions?

System Information 
Windows 7 Professional x64
MS Visual C++ 2015 Redistributable(x64)  14.0.24123
MS Visual C++ 2015 Redistributable(x86)  14.0.24123

**Comment by jpetersonme** [comment]
Forgot this:
Oracle 11.2.0 instant client

Writing queries in the editor and running them works fine.

**Comment by ibre5041** [comment]
Try version Tora.3.2.42.Release.64bit.msi. I could not reproduce the problem with copy&paste. Also save works for me. I fixed OpenFilename.

**Comment by jpetersonme** [comment]
Release 3.2.42 did fix the opening of old .sql files. Thank you. I noticed testing the copy/paste that if I use keyboard shortcuts it works just fine but if I use right-click context menus paste is grayed out in Tora when I copy from Notepad or Notepad++. I'll open a second case for this since it is a different issue. Thanks again.
