### ISSUE TITLE
tora compiled for ubuntu 17.04 machin

### ISSUE THREAD

**Issue by fadeldamen** [tora-tool/tora#85]
I get source from git and build tora 3.2.82 . The build complete  fine and make install Too Howto generate de debian package from this build I try fakeroot debian/rules binary do not work!.

help me please 

Thanks

**Comment by ibre5041** [comment]
what error do you get?

**Comment by fadeldamen** [comment]
I am run in source folder debian/rules binary


fadel@fadel:~/src/tora$ debian/rules binary
dh binary --buildsystem=cmake
   dh_testdir -O--buildsystem=cmake
   dh_update_autotools_config -O--buildsystem=cmake
   debian/rules override_dh_auto_configure
make[1]: se entra en el directorio '/home/fadel/src/tora'
dh_auto_configure -- -DCMAKE_BUILD_TYPE=Debug -DUSE_PCH=true
	mkdir -p obj-x86_64-linux-gnu
	cd obj-x86_64-linux-gnu
	cmake .. -DCMAKE_INSTALL_PREFIX=/usr -DCMAKE_VERBOSE_MAKEFILE=ON -DCMAKE_BUILD_TYPE=None -DCMAKE_INSTALL_SYSCONFDIR=/etc -DCMAKE_INSTALL_LOCALSTATEDIR=/var -DCMAKE_BUILD_TYPE=Debug -DUSE_PCH=true
CMake Warning at cmake/modules/getgit.cmake:70 (message):
  Git version dirty: v3.2-82-gd124b51a-dirty
Call Stack (most recent call first):
  CMakeLists.txt:72 (include)


Git version v3.2-82-gd124b51a-dirty
Git version major 3
Git version minor 2
Git version count 82
Git version sha1  gd124b51a
Git version short 3.2
Git version dirty Yes
Git branch master
Build tag v3.2-82-Release-gd124b51a-dirty
Build date 2018-01-08
-- Boost version: 1.63.0
-- Found the following Boost libraries:
--   system
-- Found Boost libraries for debug build: /usr/include; libs: /usr/lib/x86_64-linux-gnu
-- 
-- LIB_SUFFIX variable is not defined. It will be autodetected now.
-- You can set it manually with -DLIB_SUFFIX=<value> (64 for example)
-- CMAKE_SIZEOF_VOID_P=8
--  LIB_SUFFIX is set to '64'
-- 
-- Debug build
-- Using external loki: headers=/usr/include libs=/usr/lib/libloki.so
Qt Found OK
QScintilla2 LIBPATH "/usr/lib/x86_64-linux-gnu;/usr/lib/;/usr/local/lib"
-- Found QScintilla2: /usr/lib/libqt5scintilla2.so
--          includes: /usr/include/x86_64-linux-gnu/qt5/Qsci
QScintilla2 Found OK
-- Guessed ORACLE_OCI_VERSION value: 10G_R2 for 102
-- ORACLE_LIBRARY_CLNTSH /home/fadel/instantclient_10_2/libclntsh.so
-- ORACLE_LIBRARY_CLNTST 
-- ORACLE_LIBRARY_OCCI 
-- ORACLE_LIBRARY_XML 
-- ORACLE_LIBRARY_OCIEI 
-- Found Oracle: /home/fadel/instantclient_10_2/libclntsh.so (ORACLE_HOME='/home/fadel/instantclient_10_2')
--     includes: /home/fadel/instantclient_10_2/sdk/include
-- Found XML Oracle:  
Oracle OCI Library Found OK
-- PostgreSQL environment found: /usr/include/postgresql /usr/lib/x86_64-linux-gnu/libpq.so
-- DB2 support is disabled by user choice
-- Teradata support disabled (enable with -DENABLE_TERADATA=on)
-- Oracle OCI Library Found OK
-- -- No Oracle XDK found: ignoring
CMake Warning (dev) at cmake/modules/PrecompiledHeader.cmake:91 (GET_DIRECTORY_PROPERTY):
  Policy CMP0059 is not set: Do not treat DEFINITIONS as a built-in directory
  property.  Run "cmake --help-policy CMP0059" for policy details.  Use the
  cmake_policy command to set the policy and suppress this warning.
Call Stack (most recent call first):
  src/CMakeLists.txt:835 (ADD_PRECOMPILED_HEADER)
This warning is for project developers.  Use -Wno-dev to suppress it.

/usr/bin/c++ -DPCHCOMPILE -Wall;-ggdb3;-fPIC;-O0;-fno-inline;-rdynamic;-I/usr/include;-I/home/fadel/src/tora/extlibs/loki-extra/include;-I/usr/include/x86_64-linux-gnu/qt5;-I/usr/include/x86_64-linux-gnu/qt5/QtCore;-I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64;-I/usr/include/x86_64-linux-gnu/qt5;-I/usr/include/x86_64-linux-gnu/qt5/QtGui;-I/usr/include/x86_64-linux-gnu/qt5/QtCore;-I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64;-I/usr/include;-I/usr/include/x86_64-linux-gnu/qt5;-I/usr/include/x86_64-linux-gnu/qt5/QtNetwork;-I/usr/include/x86_64-linux-gnu/qt5/QtCore;-I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64;-I/usr/include/x86_64-linux-gnu/qt5;-I/usr/include/x86_64-linux-gnu/qt5/QtPrintSupport;-I/usr/include/x86_64-linux-gnu/qt5/QtWidgets;-I/usr/include/x86_64-linux-gnu/qt5/QtGui;-I/usr/include/x86_64-linux-gnu/qt5/QtCore;-I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64;-I/usr/include;-I/usr/include/x86_64-linux-gnu/qt5;-I/usr/include/x86_64-linux-gnu/qt5/QtSql;-I/usr/include/x86_64-linux-gnu/qt5/QtCore;-I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64;-I/usr/include/x86_64-linux-gnu/qt5;-I/usr/include/x86_64-linux-gnu/qt5/QtWidgets;-I/usr/include/x86_64-linux-gnu/qt5/QtGui;-I/usr/include/x86_64-linux-gnu/qt5/QtCore;-I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64;-I/usr/include;-I/usr/include/x86_64-linux-gnu/qt5;-I/usr/include/x86_64-linux-gnu/qt5/QtXml;-I/usr/include/x86_64-linux-gnu/qt5/QtCore;-I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64;-I/home/fadel/src/tora;-I/home/fadel/src/tora/src/precompiled;-I/home/fadel/src/tora;-I/home/fadel/src/tora/extlibs/trotl/src;-I/home/fadel/src/tora/extlibs/libermodel;-I/home/fadel/src/tora/extlibs/libantlr3cpp-3.5.3/include;-I/home/fadel/src/tora/extlibs/dtl;-I/usr/include/x86_64-linux-gnu/qt5;-I/usr/include/x86_64-linux-gnu/qt5/QtCore;-I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64;-I/usr/include/x86_64-linux-gnu/qt5;-I/usr/include/x86_64-linux-gnu/qt5/QtGui;-I/usr/include/x86_64-linux-gnu/qt5/QtCore;-I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64;-I/usr/include;-I/usr/include/x86_64-linux-gnu/qt5;-I/usr/include/x86_64-linux-gnu/qt5/QtNetwork;-I/usr/include/x86_64-linux-gnu/qt5/QtCore;-I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64;-I/usr/include/x86_64-linux-gnu/qt5;-I/usr/include/x86_64-linux-gnu/qt5/QtPrintSupport;-I/usr/include/x86_64-linux-gnu/qt5/QtWidgets;-I/usr/include/x86_64-linux-gnu/qt5/QtGui;-I/usr/include/x86_64-linux-gnu/qt5/QtCore;-I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64;-I/usr/include;-I/usr/include/x86_64-linux-gnu/qt5;-I/usr/include/x86_64-linux-gnu/qt5/QtSql;-I/usr/include/x86_64-linux-gnu/qt5/QtCore;-I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64;-I/usr/include/x86_64-linux-gnu/qt5;-I/usr/include/x86_64-linux-gnu/qt5/QtWidgets;-I/usr/include/x86_64-linux-gnu/qt5/QtGui;-I/usr/include/x86_64-linux-gnu/qt5/QtCore;-I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64;-I/usr/include;-I/usr/include/x86_64-linux-gnu/qt5;-I/usr/include/x86_64-linux-gnu/qt5/QtXml;-I/usr/include/x86_64-linux-gnu/qt5/QtCore;-I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64;-I/usr/include;-I/home/fadel/instantclient_10_2/sdk/include;-I/usr/include/postgresql;-I/usr/include/x86_64-linux-gnu/qt5/Qsci;;-DHAVE_GITREVISION_H=1;-DDEBUG;-DQT_DEBUG;-DQT_CORE_LIB;-DQT_GUI_LIB;-DQT_THREAD_LIB;-DQT;-DSCI_LEXER;-DORACLE_OCI_VER_10G_R2;-DLIBPQ_DECL_CANCEL;-DHAVE_POSTGRESQL_LIBPQ_FE_H;-DTOBUILDTYPE_RELEASE=1;-DTSQLPARSER_DLL -x c++-header -o {_output} /home/fadel/src/tora/src/precompiled/precompiled_linux.h
-- poracle /home/fadel/instantclient_10_2/libclntsh.so   trotl
-- 
-- Developer documentation (doxygen) can be generated by 'make docs'
-- 
-- TOra 3.2 will be built & installed into /usr
-- Configuring done
-- Generating done
-- Build files have been written to: /home/fadel/src/tora
	cd /home/fadel/src/tora
make[1]: se sale del directorio '/home/fadel/src/tora'
   dh_auto_build -O--buildsystem=cmake
	cd obj-x86_64-linux-gnu
	make -j1
make[1]: se entra en el directorio '/home/fadel/src/tora/obj-x86_64-linux-gnu'
make[1]: *** No se especificó ningún objetivo y no se encontró ningún makefile.  Alto.
make[1]: se sale del directorio '/home/fadel/src/tora/obj-x86_64-linux-gnu'
	cd /home/fadel/src/tora
dh_auto_build: make -j1 returned exit code 2
debian/rules:24: fallo en las instrucciones para el objetivo 'binary'
make: *** [binary] Error 2






## or only 

fadel@fadel:~/src/tora$ sudo debian/rules 
# remove some file we don't want to install
rm -f /home/fadel/src/tora/debian/tmp/usr/share/doc/tora/README.OSX
rm -f /home/fadel/src/tora/debian/tmp/usr/share/doc/tora/README.LICENSE
rm -f /home/fadel/src/tora/debian/tmp/usr/share/doc/tora/README.WINDOWS
rm -f /home/fadel/src/tora/debian/tmp/usr/share/doc/tora/INSTALL
rm -f /home/fadel/src/tora/debian/tmp/usr/share/doc/tora/COPYING
rm -f /home/fadel/src/tora/debian/tmp/usr/share/doc/tora/ChangeLog
rm -f /home/fadel/src/tora/debian/tmp/usr/share/doc/tora/changelog
# this file cannot be installed by dh_install because it has to be renamed
install --owner root --group root --mode=644 /home/fadel/src/tora/src/icons/toramini.xpm /home/fadel/src/tora/debian/tora/usr/share/icons/hicolor/16x16/apps/tora.xpm
install: no se puede crear el fichero regular '/home/fadel/src/tora/debian/tora/usr/share/icons/hicolor/16x16/apps/tora.xpm': No existe el archivo o el directorio
debian/rules:10: fallo en las instrucciones para el objetivo 'install/tora'
make: [install/tora] Error 1 (no tiene efecto)
# we have a desktop file
install --owner root --group root --mode=644 /home/fadel/src/tora/debian/tora.desktop /home/fadel/src/tora/debian/tora/usr/share/applications
install: no se puede crear el fichero regular '/home/fadel/src/tora/debian/tora/usr/share/applications': No existe el archivo o el directorio
debian/rules:10: fallo en las instrucciones para el objetivo 'install/tora'
make: [install/tora] Error 1 (no tiene efecto)

**Comment by ibre5041** [comment]
I uploaded the package onto SF. In order to build the package on 17.04 I had to:
 -  disable precompiled feaders
 -  sudo apt-get install libboost-system-dev
 -  sudo apt-get install libqt5scintilla2-dev
 -  export ORACLE_HOME=/oracle/product/12.1.0
  - export LD_LIBRARY_PATH=/oracle/product/12.1.0/lib
  - fakeroot ./debian/rules binary
