### ISSUE TITLE
No Oracle connection provider on Ubuntu 16.04

### ISSUE THREAD

**Issue by cloud81** [tora-tool/tora#86]
Hi everyone, I just installed tora 2.1.3 from Ubuntu repositories and tried also with tora 3 compiled from source, but with both version I can't see **Oracle** connection provider loaded, just MySQL or ODBC. So I can't connect to any Oracle DB instance. I have just installed on my machine the **instantclient_12_1** from Oracle.
Please could someone give me support as it just make me crazy not solving this issue.
Thanks!

**Comment by ibre5041** [comment]
Long story short, Tora package in Debian/Ubuntu is not maintaned anymore and I do not have acces to release a never version. The former maintaner built the 2x package without support for commercial sw.

Before compiling version 3 using cmake you have to export ORACLE_HOME variable (even for instantclietn). FindOracle.cmake module should handle the rest.

**Comment by cloud81** [comment]
Hi Ivan, thanks for your answer!
I'll try compiling Tora 3 with ORACLE_HOME variable exported.
I'll let you know if it works,
bye

**Comment by cloud81** [comment]
After compiling, when launching tora application from ~/tora/tora3/RBUILD/src I have error:
/home/<xxxxxxxx>/.TOra3/poracle/libtrotl.so: cannot open shared object file: No such file or directory
If I make a symbolic link to libtrotl.so in /home/ccorvino/tora/tora3/RBUILD/src/libtrotl.so on the next launch it removes the link and put this wrong link /usr/local/lib64/tora-3.2/../libtrotl.so

**Comment by ibre5041** [comment]
You have to do something like "sudo make install".

**Comment by cloud81** [comment]
I did it! Thanks! :-)
Now if I would like to make a debian package to install on my Ubuntu pc and maintain Oracle as a connection provider, what should I do? Something like `fakeroot debian/rules binary` is sufficient? I don't think so

**Comment by cloud81** [comment]
I did it! Thanks! :-)
Now if I would like to make a debian package to install on my Ubuntu pc and maintain Oracle as a connection provider, what should I do? Something like `fakeroot debian/rules binary` is sufficient? I don't think so

**Comment by cloud81** [comment]
When I try to connect to Oracle DB (with sqldeveloper it works) now I have:
ORA-12514: TNS:listener does not currently know of service requested in connect descriptor

**Comment by cloud81** [comment]
Ok I just solved problems with Oracle, now I can connect with Oracle (instantclient). Now I need to resolve problem with schema browser of MySQL, after connection, if I try opening the schema browser I get this error:
Tried to get unknown SQL (toBrowser:ViewSQL)
Strange thing: my connection provider is MySQL (QSql) not just MySQL.

**Comment by ibre5041** [comment]
should be fixed not by 7af691b50c2eb84851aa971fd7c8ef2a8374971e .  btw, mysql support does not have any maintainer. So only basic functionality is provided.
