### ISSUE TITLE
Implement unit tests that don't require X server

### ISSUE THREAD

**Issue by benapetr** [tora-tool/tora#9]
Right now it's not possible to run unit tests on server with no X server, which pretty much makes it impossible to set up a dedicated CI environment that would automatically test every commit for issues.

**Comment by benapetr** [comment]
Installing xvfb on target server sort of solves this problem, but it probably still should be fixed as unit tests don't really use graphics so there is no point in that

**Comment by ibre5041** [comment]
look at CMAKE targets test1-test5 Some of them require GUI some of them don't. At least some part of the code can be used without the main application

**Comment by benapetr** [comment]
Let's stick with xvfb then
