### ISSUE TITLE
SQL Editor  does not recognize ';' as the terminal character of a Sentence

### ISSUE THREAD

**Issue by jorgerdc** [tora-tool/tora#93]
Hi,
I have an issue  with SQL editor (tora 3.1 and 3.2).  If I have  two or more SQL sentences (one per row), tora does not recognize them  as two different sentences even that  every sentence has  as a semicolon at the end of the line.
Actually, the editor shows  a secuence of row numbers in pink  which means a  multi line
sentence which is not true.
To fix this issue I included an empty row  between every sentence, but it is not a practical solution,
especially with existing SQL scripts.

I'm not sure if this issue is also the cause  that my DML scripts does not execute as expected.

In the attached image you can see this behaviour.
-Line 5-10  Tora is not recognizing these sentences as three different sentences. It treats them
as only one. You can see the sequence of a multiline sentence in pink (1 to 6) which is wrong.

-Lines 16-20   As yo can see, there is an empty line between SQL sentences, so it works fine, but it is  not practical.
I like Tora and I  asked to my students to  install it, but they can't work well  because of this issue.

![pantallazo-2018-04-21 15-38-02](https://user-images.githubusercontent.com/755800/39088610-c0466044-457a-11e8-8710-2dfe4e36047f.png)

**Comment by ibre5041** [comment]
"fixed". anyway you can click in bottom right corner onto QsciSQL and switch onlo "Oracle" specific worsheet parser.
