### ISSUE TITLE
Compilation error of Tora 3.1 on Fedora

### ISSUE THREAD

**Issue by jorgerdc** [tora-tool/tora#94]
I'm trying to compile Tora 3.1 on Fedora 27 and I got:

```
/usr/include/qt5/QtCore/qglobal.h:1135:4: error: #error "You must build your code with position independent code if Qt was built with -reduce-relocations. " "Compile your code with -fPIC (-fPIE is not enough)."
 #  error "You must build your code with position independent code if Qt was built with -reduce-relocations. "\
    ^~~~~
/

```
To fix this I had to update CMakeLists.txt , I uncommented lines 234 -236 like this:
```
# prevent error "You must build your code with position independent code if Qt was built with..
  if (Qt5_POSITION_INDEPENDENT_CODE)
    SET(CMAKE_POSITION_INDEPENDENT_CODE ON)
  endif()
```
I'm wondering it is correct or if it is a bug ?

**Comment by ibre5041** [comment]
I do not know how to fix it. If I uncomment it it might work on Fedora but might stop working on other Linux distros :(

**Comment by ZippyDufus** [comment]
Builds through to completion without this error on Fedora 28 (gcc 8.1.1).

However, I get a core dump upon running tora.  Investigating.

**Comment by ibre5041** [comment]
The is no solution for this problem. The application should use the same/similar flags as those were used to compile Qt. But every distro uses different ones. There should not be any CMAKE_POSITION_INDEPENDENT_CODE option needed. There is an option in newer Qt versions which should be used for this purpose(Qt5Widgets_EXECUTABLE_COMPILE_FLAGS), but if I used it, it would break compatibility with other distros whose still use older Qt.

This has just to wait till recent cmake/qt5 gets onto main distros.

**Comment by onlyjob** [comment]
>  it would break compatibility with other distros whose still use older Qt.

Which is fine because older distros should be OK with older _tora_.

Please don't hold back improvements just because older distros are still around...
Why care about "older" i.e. unsupported/unmaintained Qt?

Compilation should work with current version of Qt.
