### ISSUE TITLE
Please port to QT5

### ISSUE THREAD

**Issue by onlyjob** [tora-tool/tora#95]
QT4 is legacy and Tora needs to be ported to QT5:

http://doc.qt.io/qt-5/sourcebreaks.html

CC: @djzort

**Comment by ssten** [comment]
WTF?!?
TOra for long ago supports only qt5.

**Comment by onlyjob** [comment]
I tried to build Tora on Debian 10 "Buster" but got FTBFS because _libqscintilla2-qt5-dev_ could not be found :

~~~~
QScintilla2 LIBPATH "/usr/lib/x86_64-linux-gnu;/usr/lib/;/usr/local/lib"
CMake Error at cmake/modules/FindQScintilla.cmake:96 (MESSAGE):
  QScintilla2 library not found
Call Stack (most recent call first):
  CMakeLists.txt:272 (FIND_PACKAGE)
-- Configuring incomplete, errors occurred!
~~~~

**Comment by ssten** [comment]
This means unsatisfied dependency: to build TOra with proper (system) dependency, your distr **must** provide qt5-build version of x11-libs/qscintilla.

It is not TOra, but downstream issue.

**Comment by onlyjob** [comment]
The issue seems that [FindQScintilla.cmake](https://github.com/tora-tool/tora/blob/master/cmake/modules/FindQScintilla.cmake) does a poor job as it fails to detect an installed library.

Ironically my observation is confirmed by commit message of the last commit that touched the file:

>  tora doesn't do a good job of finding qscintilla2 library installed on the system.

@ssten, your attitude is unhelpful. :(

**Comment by mkyral** [comment]
@onlyjob   sorry, but title of this issue is wrong. Tora is already using qt5 as @ssten pointed out.

And You also provided insufficient info. How we should know, that you have libqscintilla2-qt5-dev already installed?

Proper bug report should contain something like "Tora is not able to find installed libqscintilla2-qt5 libs".

**Comment by ssten** [comment]
@mkyral, for my experience your question is still incomplete.
At least for Gentoo downstream I can say, that slots (Gentoo feature to use semi-time installed different versions of a package) was **not** used for *x11-libs/qscintilla*. So, it could be built either with *qt4* support or with *qt5*, but not with both of them.

So, for Debian build we may need not only libqscintilla2-qt5-dev package state, but also libqscintilla2-qt4-dev.

**Comment by a17r** [comment]
Please note that Gentoo has to `sed /FIND_LIBRARY(QSCINTILLA_LIBRARY/s/qt5scintilla2/qscintilla2_qt5/` over FindQScintilla.cmake at least for version 3.2.

**Comment by ibre5041** [comment]
detection of QScintilla2 libraries, especially QT5 ones is PITA. every distribution names them differently. When I fix it for one distro, it stops working on some other. There is still possibililty to compile it using cmake -DWANT_INTERNAL_QSCINTILLA=ON. If you have a patch I will apply it.
